version: "3.8"
services: 
  nextjs:
    container_name: tok-web
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_YM_ID=95115536
    ports:
      - 3000:3000
  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: unless-stopped
