export const takt_c1 = {
  id: 71,
  title: "takt-c1",
  modelsSlider: [
    "/images/products/takt/c1/models/1.jpg",
    "/images/products/takt/c1/models/2.jpg",
    "/images/products/takt/c1/models/3.jpg",
    "/images/products/takt/c1/models/4.jpg",
    "/images/products/takt/c1/models/5.jpg",
    "/images/products/takt/c1/models/6.jpg",
    "/images/products/takt/c1/models/7.jpg",
    "/images/products/takt/c1/models/8.jpg",
    "/images/products/takt/c1/models/9.jpg",
  ],
  description:
  "Модульная серия диванов ТАКТ разработана в соответствии с последними мировыми тенденциями дизайна мебели, сочетает в себе элегантность и функциональность. Доминируют простые и четкие линии, что придает ощущение прозрачности и гармонии. Долговечная и надежная конструкция с использованием дерева, металла, гипоаллергенных наполнителей и текстиля.\n\nИдеальный вариант для больших пространств. Представляет собой модульную систему, которая может придать интерьеру индивидуальный характер. Создайте свою неповторимую комбинацию из 18 типовых модулей серии диванов ТАКТ.\n\n*В стоимость не входят подголовники и подушки.",
  designer: "Сергей Беляков",
  dateOfCreation: 2024,
  countertop: [
    "ткань категория 1",
    "ткань категория 2",
    "ткань категория 3",
    "ткань категория 4",
  ],
  sizesSlider: [
    "/images/products/takt/c1/sizes/1.jpg",
    "/images/products/takt/c1/sizes/2.jpg",
    "/images/products/takt/c1/sizes/3.jpg",
    "/images/products/takt/c1/sizes/4.jpg",
    "/images/products/takt/c1/sizes/5.jpg",
    "/images/products/takt/c1/sizes/6.jpg",
    "/images/products/takt/c1/sizes/7.jpg",
    "/images/products/takt/c1/sizes/8.jpg",
    "/images/products/takt/c1/sizes/9.jpg",
    "/images/products/takt/c1/sizes/10.jpg",
    "/images/products/takt/c1/sizes/11.jpg",
  ],
  visualisations: [
    "/images/products/takt/c1/interior/1.jpg",
    "/images/products/takt/c1/interior/2.jpg",
    "/images/products/takt/c1/interior/3.jpg",
    "/images/products/takt/c1/interior/4.jpg",
    "/images/products/takt/c1/interior/5.jpg",
    "/images/products/takt/c1/interior/6.jpg",
    "/images/products/takt/c1/interior/7.jpg",
  ],
  designersProjects: [],
  price: [464400],
  params: {
    "ткань категория 1": 464400,
    "ткань категория 2": 488400,
    "ткань категория 3": 536400,
    "ткань категория 4": 566400,
  },
  category: "SOFA",
  name: "такт с1",
  previewImg: "/images/products/takt/c1/preview.jpg",
  position: 3.5,
  mobilePosition: 6.5,
  model: "https://disk.yandex.ru/d/PNHX_lczTAQjSw",
  collage: "https://disk.yandex.ru/d/jzMWLKozt-Gueg",
  tags: ["диван"],
};
