export const takt_c8 = {
    id: 78,
    title: "takt-c8",
    modelsSlider: [
      "/images/products/takt/c8/models/1.jpg",
      "/images/products/takt/c8/models/2.jpg",
      "/images/products/takt/c8/models/3.jpg",
      "/images/products/takt/c8/models/4.jpg",
      "/images/products/takt/c8/models/5.jpg",
      "/images/products/takt/c8/models/6.jpg",
      "/images/products/takt/c8/models/7.jpg",
      "/images/products/takt/c8/models/8.jpg",
    ],
    description:
    "Модульная серия диванов ТАКТ разработана в соответствии с последними мировыми тенденциями дизайна мебели, сочетает в себе элегантность и функциональность. Доминируют простые и четкие линии, что придает ощущение прозрачности и гармонии. Долговечная и надежная конструкция с использованием дерева, металла, гипоаллергенных наполнителей и текстиля.\n\nИдеальный вариант для больших пространств. Представляет собой модульную систему, которая может придать интерьеру индивидуальный характер. Создайте свою неповторимую комбинацию из 18 типовых модулей серии диванов ТАКТ.\n\n*В стоимость не входят подголовники и подушки.",
    designer: "Сергей Беляков",
    dateOfCreation: 2024,
    countertop: [
      "ткань категория 1",
      "ткань категория 2",
      "ткань категория 3",
      "ткань категория 4",
    ],
    sizesSlider: [
      "/images/products/takt/c8/sizes/1.jpg",
      "/images/products/takt/c8/sizes/2.jpg",
      "/images/products/takt/c8/sizes/3.jpg",
      "/images/products/takt/c8/sizes/4.jpg",
      "/images/products/takt/c8/sizes/5.jpg",
      "/images/products/takt/c8/sizes/6.jpg",
      "/images/products/takt/c8/sizes/7.jpg",
      "/images/products/takt/c8/sizes/8.jpg",
      "/images/products/takt/c8/sizes/9.jpg",
      "/images/products/takt/c8/sizes/10.jpg",
      "/images/products/takt/c8/sizes/11.jpg",
    ],
    visualisations: [
      // "/images/products/takt/c8/interior/1.jpg",
      "/images/products/takt/c8/interior/2.jpg",
      "/images/products/takt/c8/interior/3.jpg",
      "/images/products/takt/c8/interior/4.jpg",
    ],
    designersProjects: [],
    price: [520200],
    params: {
      "ткань категория 1": 520200,
      "ткань категория 2": 556200,
      "ткань категория 3": 628200,
      "ткань категория 4": 673200,
    },
    category: "SOFA",
    name: "такт с8",
    previewImg: "/images/products/takt/c8/preview.jpg",
    position: -2,
    mobilePosition: -2,
    model: "https://disk.yandex.ru/d/PNHX_lczTAQjSw",
    collage: "https://disk.yandex.ru/d/inEwAgkrJvf6JQ",
    tags: ["диван"],
  };
  