export const takt_c9 = {
    id: 79,
    title: "takt-c9",
    modelsSlider: [
      "/images/products/takt/c9/models/1.jpg",
      "/images/products/takt/c9/models/2.jpg",
      "/images/products/takt/c9/models/3.jpg",
      "/images/products/takt/c9/models/4.jpg",
      "/images/products/takt/c9/models/5.jpg",
      "/images/products/takt/c9/models/6.jpg",
      "/images/products/takt/c9/models/7.jpg",
      "/images/products/takt/c9/models/8.jpg",
    ],
    description:
    "Модульная серия диванов ТАКТ разработана в соответствии с последними мировыми тенденциями дизайна мебели, сочетает в себе элегантность и функциональность. Доминируют простые и четкие линии, что придает ощущение прозрачности и гармонии. Долговечная и надежная конструкция с использованием дерева, металла, гипоаллергенных наполнителей и текстиля.\n\nИдеальный вариант для больших пространств. Представляет собой модульную систему, которая может придать интерьеру индивидуальный характер. Создайте свою неповторимую комбинацию из 18 типовых модулей серии диванов ТАКТ.\n\n*В стоимость не входят подголовники и подушки.",
    designer: "Сергей Беляков",
    dateOfCreation: 2024,
    countertop: [
      "ткань категория 1",
      "ткань категория 2",
      "ткань категория 3",
      "ткань категория 4",
    ],
    sizesSlider: [
      "/images/products/takt/c9/sizes/1.jpg",
      "/images/products/takt/c9/sizes/2.jpg",
      "/images/products/takt/c9/sizes/3.jpg",
      "/images/products/takt/c9/sizes/4.jpg",
      "/images/products/takt/c9/sizes/5.jpg",
      "/images/products/takt/c9/sizes/6.jpg",
      "/images/products/takt/c9/sizes/7.jpg",
      "/images/products/takt/c9/sizes/8.jpg",
      "/images/products/takt/c9/sizes/9.jpg",
      "/images/products/takt/c9/sizes/10.jpg",
      "/images/products/takt/c9/sizes/11.jpg",
      "/images/products/takt/c9/sizes/12.jpg",
    ],
    visualisations: [
      "/images/products/takt/c9/interior/1.jpg",
      "/images/products/takt/c9/interior/2.jpg",
      "/images/products/takt/c9/interior/3.jpg",
      "/images/products/takt/c9/interior/4.jpg",
    ],
    designersProjects: [],
    price: [495600],
    params: {
      "ткань категория 1": 495600,
      "ткань категория 2": 531600,
      "ткань категория 3": 603600,
      "ткань категория 4": 648600,
    },
    category: "SOFA",
    name: "такт с9",
    previewImg: "/images/products/takt/c9/preview.jpg",
    position: -2,
    mobilePosition: -2,
    model: "https://disk.yandex.ru/d/BtLHL09Eb_TuUg",
    collage: "https://disk.yandex.ru/d/I466UPmtaoBmJw",
    tags: ["диван"],
  };
  