export const takt_md = {
    id: 80,
    title: "takt-md",
    modelsSlider: [
      "/images/products/takt/md/models/1.jpg",
      "/images/products/takt/md/models/2.jpg",
      "/images/products/takt/md/models/3.jpg",
      "/images/products/takt/md/models/4.jpg",
      "/images/products/takt/md/models/5.jpg",
      "/images/products/takt/md/models/6.jpg",
      "/images/products/takt/md/models/7.jpg",
      "/images/products/takt/md/models/8.jpg",
    ],
    description:
    "Модульная серия диванов ТАКТ разработана в соответствии с последними мировыми тенденциями дизайна мебели, сочетает в себе элегантность и функциональность. Доминируют простые и четкие линии, что придает ощущение прозрачности и гармонии. Долговечная и надежная конструкция с использованием дерева, металла, гипоаллергенных наполнителей и текстиля.\n\nИдеальный вариант для больших пространств. Представляет собой модульную систему, которая может придать интерьеру индивидуальный характер. Создайте свою неповторимую комбинацию из 18 типовых модулей серии диванов ТАКТ.\n\n*В стоимость не входят подголовники и подушки.",
    designer: "Сергей Беляков",
    dateOfCreation: 2024,
    countertop: [
      "ткань категория 1",
      "ткань категория 2",
      "ткань категория 3",
      "ткань категория 4",
    ],
    sizesSlider: [
      "/images/products/takt/md/sizes/1.jpg",
      "/images/products/takt/md/sizes/2.jpg",
      "/images/products/takt/md/sizes/3.jpg",
      "/images/products/takt/md/sizes/4.jpg",
      "/images/products/takt/md/sizes/5.jpg",
      "/images/products/takt/md/sizes/6.jpg",
      "/images/products/takt/md/sizes/7.jpg",
      "/images/products/takt/md/sizes/8.jpg",
      "/images/products/takt/md/sizes/9.jpg",
      "/images/products/takt/md/sizes/10.jpg",
    ],
    visualisations: [
      "/images/products/takt/md/interior/1.jpg",
      "/images/products/takt/md/interior/2.jpg",
      "/images/products/takt/md/interior/3.jpg",
    ],
    designersProjects: [],
    price: [240900],
    params: {
      "ткань категория 1": 240900,
      "ткань категория 2": 252900,
      "ткань категория 3": 276900,
      "ткань категория 4": 291900,
    },
    category: "SOFA",
    name: "такт md",
    previewImg: "/images/products/takt/md/preview.jpg",
    position: -2,
    mobilePosition: -2,
    model: "https://disk.yandex.ru/d/PNHX_lczTAQjSw",
    tags: ["диван"],
  };
  