export type TMaterial = {
  id: number;
  name: string;
  type?: string;
  img: string;
};

export type TMaterialGroup = {
  id: number;
  title:
    | "hpl"
    | "fenix ntm"
    | "эмаль"
    | "эмаль с фактурой дуба"
    | "керамика"
    | "тонировка дуба"
    | "металл"
    | "металл металлик"
    | "архитектурный бетон"
    | "кожа категория 1"
    | "кожа категория 2"
    | "ткань категория 1"
    | "ткань категория 2"
    | "ткань категория 3"
    | "нержавеющая сталь";
  furnish: string;
  base?: string;
  hem?: string;
  manufacturer?: string;
  description?: string;
  materials: TMaterial[];
};

export const HPL: TMaterialGroup = {
  id: 1,
  title: "hpl",
  furnish: "hpl",
  base: "мдф",
  hem: "эмаль",
  manufacturer: "италия",
  description:
    "Пластик высокого давления с декоративной поверхностью, современный композитный материал, получаемый из крафт бумаги, термоактивных смол и защитного слоя. В структуре практически нет пор, поэтому поверхности легко моются, в них не задерживаются частицы пищи, пыли, не развиваются микробы. Готовое изделие приобретает прочность, монолитность, становится стойким к механическим воздействиям, влажности и температуре. С помощью пресс-пластины пластику можно придать необходимую фактуру.",
  materials: [
    {
      id: 1,
      name: "3433",
      type: "черный",
      img: "/images/materials/hpl/3433.jpg",
    },
    {
      id: 2,
      name: "3445",
      type: "пул средний",
      img: "/images/materials/hpl/3445.jpg",
    },
    {
      id: 3,
      name: "3446",
      type: "пул темный",
      img: "/images/materials/hpl/3446.jpg",
    },
    {
      id: 4,
      name: "3447",
      type: "пул светлый",
      img: "/images/materials/hpl/3447.jpg",
    },
    {
      id: 5,
      name: "3482",
      type: "самас",
      img: "/images/materials/hpl/3482.jpg",
    },
    {
      id: 6,
      name: "3493",
      type: "калакатта",
      img: "/images/materials/hpl/3493.jpg",
    },
  ],
};

export const FenixNTM: TMaterialGroup = {
  id: 2,
  title: "fenix ntm",
  furnish: "fenix ntm",
  base: "мдф",
  hem: "эмаль",
  manufacturer: "италия",
  description:
    "Матовый нанотехнологичный материал произведённый на основе акриловых смол, обработанный электронно-лучевым процессом.Низкая светоотражающая способность, препятствующая образованию бликов при естественном и искусственном освещении. Покрытие soft-touch, которое дарит приятные тактильные ощущения. Устойчивость к образованию отпечатков пальцев. Поверхность из FENIX NTM не нужно протирать после каждого прикосновения. Стойкость к термическим воздействиям. Материал способен выдерживать контакт с разогретыми до 200 градусов предметами в течение 20 минут без ущерба для внешнего вида. Влагостойкость. Покрытие из термоактивных смол не впитывает воду, не гниет и не поражается плесенью, не разбухает и не расслаивается при контакте с водой. Устойчивость к воздействию бытовой химии. Для очистки нанопластика можно использовать обычные моющие средства без абразивных компонентов.",
  materials: [
    {
      id: 1,
      name: "0032",
      type: "белый",
      img: "/images/materials/fenix_ntm/0032.jpg",
    },
    {
      id: 2,
      name: "0717",
      type: "серо-бежевый",
      img: "/images/materials/fenix_ntm/0717.jpg",
    },
    {
      id: 3,
      name: "0719",
      type: "бежевый",
      img: "/images/materials/fenix_ntm/0719.jpg",
    },
    {
      id: 4,
      name: "0720",
      type: "пыльно-чёрный",
      img: "/images/materials/fenix_ntm/0720.jpg",
    },
    {
      id: 5,
      name: "0724",
      type: "антрацит",
      img: "/images/materials/fenix_ntm/0724.jpg",
    },
    {
      id: 6,
      name: "0725",
      type: "светло-серый",
      img: "/images/materials/fenix_ntm/0725.jpg",
    },
    {
      id: 7,
      name: "0748",
      type: "серый шёлк",
      img: "/images/materials/fenix_ntm/0748.jpg",
    },
    {
      id: 8,
      name: "0749",
      type: "кофейный",
      img: "/images/materials/fenix_ntm/0749.jpg",
    },
    {
      id: 9,
      name: "0750",
      type: "тёмно-серая зелень",
      img: "/images/materials/fenix_ntm/0750.jpg",
    },
    {
      id: 10,
      name: "0751",
      type: "бурый",
      img: "/images/materials/fenix_ntm/0751.jpg",
    },
    {
      id: 11,
      name: "0752",
      type: "серый",
      img: "/images/materials/fenix_ntm/0752.jpg",
    },
    {
      id: 12,
      name: "0754",
      type: "тёмный ультрамарин",
      img: "/images/materials/fenix_ntm/0754.jpg",
    },
    {
      id: 13,
      name: "0770",
      type: "бургунди",
      img: "/images/materials/fenix_ntm/0770.jpg",
    },
    {
      id: 14,
      name: "0771",
      type: "синяя пастель",
      img: "/images/materials/fenix_ntm/0771.jpg",
    },
    {
      id: 15,
      name: "0772",
      type: "жёлтая пастель",
      img: "/images/materials/fenix_ntm/0772.jpg",
    },
    {
      id: 16,
      name: "0773",
      type: "пыльно-зелёный",
      img: "/images/materials/fenix_ntm/0773.jpg",
    },
  ],
};

export const Enamel: TMaterialGroup = {
  id: 3,
  title: "эмаль",
  furnish: "эмаль",
  base: "мдф",
  hem: "",
  manufacturer: "италия",
  description:
    "Порошковая краска представляет собой твердую многокомпонентную композицию, которая под воздействием высокой температуры образует тончайшую пленку, плотно сцепленную с окрашиваемой поверхностью.",
  materials: [
    {
      id: 1,
      name: "1013",
      type: "светлый беж",
      img: "/images/materials/enamel/1013.jpg",
    },
    {
      id: 2,
      name: "1020",
      type: "болотный",
      img: "/images/materials/enamel/1020.jpg",
    },
    {
      id: 3,
      name: "0002500",
      type: "пыльно-чёрный",
      img: "/images/materials/enamel/0002500.jpg",
    },
    {
      id: 4,
      name: "6004",
      type: "тёмно-бирюзовый",
      img: "/images/materials/enamel/6004.jpg",
    },
    {
      id: 5,
      name: "7016",
      type: "антрацит",
      img: "/images/materials/enamel/7016.jpg",
    },
    {
      id: 6,
      name: "7035",
      type: "светло-серый",
      img: "/images/materials/enamel/7035.jpg",
    },
    {
      id: 7,
      name: "7037",
      type: "серый",
      img: "/images/materials/enamel/7037.jpg",
    },
    {
      id: 8,
      name: "8015",
      type: "бурый",
      img: "/images/materials/enamel/8015.jpg",
    },
    {
      id: 9,
      name: "8019",
      type: "кофейный",
      img: "/images/materials/enamel/8019.jpg",
    },
    {
      id: 10,
      name: "8023",
      type: "кирпичный",
      img: "/images/materials/enamel/8023.jpg",
    },
    {
      id: 11,
      name: "9005",
      type: "чёрный",
      img: "/images/materials/enamel/9005.jpg",
    },
    {
      id: 12,
      name: "9016",
      type: "белый",
      img: "/images/materials/enamel/9016.jpg",
    },
    {
      id: 13,
      name: "0204020",
      type: "бургунди",
      img: "/images/materials/enamel/0204020.jpg",
    },
    {
      id: 14,
      name: "0706010",
      type: "серо-бежевый",
      img: "/images/materials/enamel/0706010.jpg",
    },
    {
      id: 15,
      name: "0707050",
      type: "жёлтая пастель",
      img: "/images/materials/enamel/0707050.jpg",
    },
    {
      id: 16,
      name: "0806005",
      type: "серый шёлк",
      img: "/images/materials/enamel/0806005.jpg",
    },
    {
      id: 17,
      name: "0808010",
      type: "бежевый",
      img: "/images/materials/enamel/0808010.jpg",
    },
    {
      id: 18,
      name: "1605015",
      type: "пыльно-зелёный",
      img: "/images/materials/enamel/1605015.jpg",
    },
    {
      id: 19,
      name: "1804005",
      type: "тёмно-серая зелень",
      img: "/images/materials/enamel/1804005.jpg",
    },
    {
      id: 20,
      name: "2505015",
      type: "синяя пастель",
      img: "/images/materials/enamel/2505015.jpg",
    },
    {
      id: 21,
      name: "2603015",
      type: "тёмный ультрамарин",
      img: "/images/materials/enamel/2603015.jpg",
    },
    {
      id: 22,
      name: "7006",
      type: "кофе с молоком",
      img: "/images/materials/enamel/7006.jpg",
    },
  ],
};

export const EnamelWithOakTexture: TMaterialGroup = {
  id: 3,
  title: "эмаль с фактурой дуба",
  furnish: "эмаль",
  base: "шпон / массив дуба",
  hem: "",
  manufacturer: "италия",
  description:
    "Порошковая краска представляет собой твердую многокомпонентную композицию, которая под воздействием высокой температуры образует тончайшую пленку, плотно сцепленную с окрашиваемой поверхностью.",
  materials: [
    {
      id: 1,
      name: "1013",
      type: "светлый беж",
      img: "/images/materials/enamel_oak/1013.jpg",
    },
    {
      id: 2,
      name: "1020",
      type: "болотный",
      img: "/images/materials/enamel_oak/1020.jpg",
    },
    {
      id: 3,
      name: "0002500",
      type: "пыльно-чёрный",
      img: "/images/materials/enamel_oak/0002500.jpg",
    },
    {
      id: 4,
      name: "6004",
      type: "тёмно-бирюзовый",
      img: "/images/materials/enamel_oak/6004.jpg",
    },
    {
      id: 5,
      name: "7016",
      type: "антрацит",
      img: "/images/materials/enamel_oak/7016.jpg",
    },
    {
      id: 6,
      name: "7035",
      type: "светло-серый",
      img: "/images/materials/enamel_oak/7035.jpg",
    },
    {
      id: 7,
      name: "7037",
      type: "серый",
      img: "/images/materials/enamel_oak/7037.jpg",
    },
    {
      id: 8,
      name: "8015",
      type: "бурый",
      img: "/images/materials/enamel_oak/8015.jpg",
    },
    {
      id: 9,
      name: "8019",
      type: "кофейный",
      img: "/images/materials/enamel_oak/8019.jpg",
    },
    {
      id: 10,
      name: "8023",
      type: "кирпичный",
      img: "/images/materials/enamel_oak/8023.jpg",
    },
    {
      id: 11,
      name: "9005",
      type: "чёрный",
      img: "/images/materials/enamel_oak/9005.jpg",
    },
    {
      id: 12,
      name: "9016",
      type: "белый",
      img: "/images/materials/enamel_oak/9016.jpg",
    },
    {
      id: 13,
      name: "0204020",
      type: "бургунди",
      img: "/images/materials/enamel_oak/0204020.jpg",
    },
    {
      id: 14,
      name: "0706010",
      type: "серо-бежевый",
      img: "/images/materials/enamel_oak/0706010.jpg",
    },
    {
      id: 15,
      name: "0707050",
      type: "жёлтая пастель",
      img: "/images/materials/enamel_oak/0707050.jpg",
    },
    {
      id: 16,
      name: "0806005",
      type: "серый шёлк",
      img: "/images/materials/enamel_oak/0806005.jpg",
    },
    {
      id: 17,
      name: "0808010",
      type: "бежевый",
      img: "/images/materials/enamel_oak/0808010.jpg",
    },
    {
      id: 18,
      name: "1605015",
      type: "пыльно-зелёный",
      img: "/images/materials/enamel_oak/1605015.jpg",
    },
    {
      id: 19,
      name: "1804005",
      type: "тёмно-серая зелень",
      img: "/images/materials/enamel_oak/1804005.jpg",
    },
    {
      id: 20,
      name: "2505015",
      type: "синяя пастель",
      img: "/images/materials/enamel_oak/2505015.jpg",
    },
    {
      id: 21,
      name: "2603015",
      type: "тёмный ультрамарин",
      img: "/images/materials/enamel_oak/2603015.jpg",
    },
    {
      id: 22,
      name: "7006",
      type: "кофе с молоком",
      img: "/images/materials/enamel_oak/7006.jpg",
    },
  ],
};

export const Ceramics: TMaterialGroup = {
  id: 4,
  title: "керамика",
  furnish: "керамика",
  base: "мдф",
  hem: "эмаль",
  manufacturer: "италия",
  description:
    "Листовая керамика производится из природных материалов под воздействием высоких температур и не содержит в своём составе вредных для человека веществ. Керамика относится к материалам, пригодным для полной повторной переработки. Рисунок у каждой плиты уникальный, что позволяет привнести индивидуальность в интерьер.",
  materials: [
    {
      id: 1,
      name: "mbsv",
      type: "калакатта",
      img: "/images/materials/ceramics/mbsv.jpg",
    },
    {
      id: 2,
      name: "mcov",
      type: "калакатта",
      img: "/images/materials/ceramics/mcov.jpg",
    },
    {
      id: 3,
      name: "mdcb",
      type: "беж",
      img: "/images/materials/ceramics/mdcb.jpg",
    },
    {
      id: 4,
      name: "mngb",
      type: "чёрный",
      img: "/images/materials/ceramics/mngb.jpg",
    },
    {
      id: 5,
      name: "mpgb",
      type: "серый",
      img: "/images/materials/ceramics/mpgb.jpg",
    },
    {
      id: 6,
      name: "cvo",
      type: "калакатта",
      img: "/images/materials/ceramics/cvol.jpg",
    },
    {
      id: 7,
      name: "solo",
      type: "белый",
      img: "/images/materials/ceramics/w-solo.jpg",
    },
    {
      id: 8,
      name: "solo",
      type: "черный",
      img: "/images/materials/ceramics/b-solo.jpg",
    },
    {
      id: 9,
      name: "millennium black",
      type: "",
      img: "/images/materials/ceramics/m_black.jpg",
    },
    {
      id: 10,
      name: "millennium pure",
      type: "",
      img: "/images/materials/ceramics/m_pure.jpg",
    },
    {
      id: 11,
      name: "millennium silver",
      type: "",
      img: "/images/materials/ceramics/m_silver.jpg",
    },
  ],
};

export const Oak_tinting: TMaterialGroup = {
  id: 5,
  title: "тонировка дуба",
  furnish: "тонировка дуба",
  base: "шпон дуба, массив дуба",
  hem: "мдф",
  manufacturer: "россия",
  description:
    "Тонировка - это покрытие дерева пропиткой, которая изменяет оттенок дерева. Тонировка (тонирование, травление) дерева позволяет усилить выразительный рисунок среза древесины, устранить дефекты и получить мебельный материал с глубоким однородным оттенком.\n\nШпон дуба - Натуральный материал с превосходными декоративными свойствами, тонкая пластина, срезанная с цельного деревянного бруска. При изготовлении шпон дуба подвергают специальной обработке, улучшающей характеристики материала. Для придания необходимого оттенка его тонируют, выбеливают или воскуют, сохраняя текстурный рисунок, структуру и эксплуатационные свойства древесины. Готовый шпон склеивают с основой - МДФ (плотно спрессованный слой древесины, под теплом и давлением) и покрывают специальным составом для практичности использования в обеденной зоне.\n\nМассив дуба - Натуральный материал из твердой породы дерева. Имеет красивую текстуру с выделением древесных волокон. При изготовлении массив дуба подвергают специальной обработке, улучшающей характеристики материала. Для придания необходимого оттенка его тонируют, выбеливают или воскуют, сохраняя текстурный рисунок, структуру и эксплуатационные свойства древесины. Мебель из массива дуба не только красивая, но также очень крепкая и надежная.",
  materials: [
    {
      id: 1,
      name: "1000",
      type: "натуральный",
      img: "/images/materials/oak_tinting/1000.jpg",
    },
    {
      id: 2,
      name: "1022",
      type: "белёный",
      img: "/images/materials/oak_tinting/1022.jpg",
    },
    {
      id: 3,
      name: "1029",
      type: "венге",
      img: "/images/materials/oak_tinting/1029.jpg",
    },
    {
      id: 4,
      name: "1080",
      type: "табак",
      img: "/images/materials/oak_tinting/1080.jpg",
    },
    {
      id: 5,
      name: "1109",
      type: "копчёный",
      img: "/images/materials/oak_tinting/1109.jpg",
    },
    {
      id: 6,
      name: "1209",
      type: "орех",
      img: "/images/materials/oak_tinting/1209.jpg",
    },
    {
      id: 7,
      name: "1309",
      type: "тёмный орех",
      img: "/images/materials/oak_tinting/1309.jpg",
    },
    {
      id: 8,
      name: "2080",
      type: "тёмный табак",
      img: "/images/materials/oak_tinting/2080.jpg",
    },
  ],
};

export const Metal: TMaterialGroup = {
  id: 6,
  title: "металл",
  furnish: "порошковая краска",
  base: "металл",
  hem: "",
  manufacturer: "россия",
  description:  "Порошковая краска представляет собой твердую многокомпонентную композицию, которая под воздействием высокой температуры образует тончайшую пленку, плотно сцепленную с окрашиваемой поверхностью.",
  materials: [
    {
      id: 1,
      name: "1013",
      type: "светлый беж",
      img: "/images/materials/metal/1013.jpg",
    },
    {
      id: 2,
      name: "7016",
      type: "антрацит",
      img: "/images/materials/metal/7016.jpg",
    },
    {
      id: 3,
      name: "7035",
      type: "светло-серый",
      img: "/images/materials/metal/7035.jpg",
    },
    {
      id: 4,
      name: "7037",
      type: "серый",
      img: "/images/materials/metal/7037.jpg",
    },
    {
      id: 5,
      name: "8015",
      type: "бурый",
      img: "/images/materials/metal/8015.jpg",
    },
    {
      id: 6,
      name: "8019",
      type: "кофейный",
      img: "/images/materials/metal/8019.jpg",
    },
    {
      id: 7,
      name: "9005",
      type: "черный",
      img: "/images/materials/metal/9005.jpg",
    },
    {
      id: 8,
      name: "9016",
      type: "белый",
      img: "/images/materials/metal/9016.jpg",
    },
    {
      id: 9,
      name: "7006",
      type: "кофе с молоком",
      img: '/images/materials/metal/7006.jpg',
    }
  ],
};

export const Metallic: TMaterialGroup = {
  id: 7,
  title: "металл металлик",
  furnish: "порошковая краска",
  base: "металл",
  hem: "",
  manufacturer: "россия",
  description: "Порошковая краска представляет собой твердую многокомпонентную композицию, которая под воздействием высокой температуры образует тончайшую пленку, плотно сцепленную с окрашиваемой поверхностью.",
  materials: [
    {
      id: 1,
      name: "бронза мт",
      img: "/images/materials/metal_metallic/bronze_mt.jpg",
    },
    {
      id: 2,
      name: "медь мт",
      img: "/images/materials/metal_metallic/cuprum_mt.jpg",
    },
    {
      id: 3,
      name: "золото мт",
      img: "/images/materials/metal_metallic/gold_mt.jpg",
    },
    {
      id: 4,
      name: "графит мт",
      img: "/images/materials/metal_metallic/graphite_mt.jpg",
    },
    {
      id: 5,
      name: "никель мт 1035",
      img: "/images/materials/metal_metallic/nickel_mt_1035.jpg",
    },
    {
      id: 6,
      name: "перламутр мт 7032",
      img: "/images/materials/metal_metallic/perl_mt_7032.jpg",
    },
  ],
};


export const Architectural_concrete: TMaterialGroup = {
  id: 8,
  title: "архитектурный бетон",
  furnish: "архитектурный бетон",
  base: "архитектурный бетон",
  hem: "",
  manufacturer: "россия",
  description:
    "Строительная смесь на основе цементно-песчаного состава с различными минеральными и неорганическими добавками. Архитектурный бетон несёт опорную и конструктивную нагрузку.",
  materials: [
    {
      id: 1,
      name: "01",
      type: "светло-серый",
      img: "/images/materials/architectural_concrete/01.jpg",
    },
    {
      id: 2,
      name: "02",
      type: "серый",
      img: "/images/materials/architectural_concrete/02.jpg",
    },
    {
      id: 3,
      name: "03",
      type: "тёмно-серый",
      img: "/images/materials/architectural_concrete/03.jpg",
    },
  ],
};

export const Leather_cat1: TMaterialGroup = {
  id: 9,
  title: "кожа категория 1",
  furnish: "натуральная кожа",
  base: "",
  hem: "",
  manufacturer: "италия",
  description: "Однотонная матовая кожа с небольшим маслянистым блеском.  Кожа с полностью скорректированным лицом с крупным тиснением. При производстве используются водные красители. Кожа покрыта защитным слоем, что существенно облегчает уход за мебелью.",
  materials: [
    {
      id: 1,
      name: "801",
      img: "/images/materials/genuine_leather/cat1/801.jpg",
    },
    {
      id: 2,
      name: "834",
      img: "/images/materials/genuine_leather/cat1/834.jpg",
    },
    {
      id: 3,
      name: "821",
      img: "/images/materials/genuine_leather/cat1/821.jpg",
    },
    {
      id: 4,
      name: "819",
      img: "/images/materials/genuine_leather/cat1/819.jpg",
    },
    {
      id: 5,
      name: "831",
      img: "/images/materials/genuine_leather/cat1/831.jpg",
    },
    {
      id: 6,
      name: "807",
      img: "/images/materials/genuine_leather/cat1/807.jpg",
    },
    {
      id: 7,
      name: "837",
      img: "/images/materials/genuine_leather/cat1/837.jpg",
    },
    {
      id: 8,
      name: "836",
      img: "/images/materials/genuine_leather/cat1/836.jpg",
    },
    {
      id: 9,
      name: "806",
      img: "/images/materials/genuine_leather/cat1/806.jpg",
    },
    {
      id: 10,
      name: "812",
      img: "/images/materials/genuine_leather/cat1/812.jpg",
    },
    {
      id: 11,
      name: "808",
      img: "/images/materials/genuine_leather/cat1/808.jpg",
    },
    {
      id: 12,
      name: "835",
      img: "/images/materials/genuine_leather/cat1/835.jpg",
    },
    {
      id: 13,
      name: "820",
      img: "/images/materials/genuine_leather/cat1/820.jpg",
    },
    {
      id: 14,
      name: "803",
      img: "/images/materials/genuine_leather/cat1/803.jpg",
    },
    {
      id: 15,
      name: "802",
      img: "/images/materials/genuine_leather/cat1/802.jpg",
    },
  ],
};

export const Leather_cat2: TMaterialGroup = {
  id: 10,
  title: "кожа категория 2",
  furnish: "натуральная кожа",
  base: "",
  hem: "",
  manufacturer: "италия",
  description: "SUAVE – однотонная матовая кожа, c натуральным лицом и природным строением мереи. При производстве используются только европейские шкуры высокого класса и применяют красители на водной основе. Легкое защитное покрытие значительно облегчает уход за изделиями из кожи.",
  materials: [
    {
      id: 1,
      name: "acciaio",
      img: "/images/materials/genuine_leather/cat2/acciaio.jpg",
    },
    {
      id: 2,
      name: "cappuccino",
      img: "/images/materials/genuine_leather/cat2/cappuccino.jpg",
    },
    {
      id: 3,
      name: "corteccia",
      img: "/images/materials/genuine_leather/cat2/corteccia.jpg",
    },
    {
      id: 4,
      name: "fango",
      img: "/images/materials/genuine_leather/cat2/fango.jpg",
    },
    {
      id: 5,
      name: "gotico",
      img: "/images/materials/genuine_leather/cat2/gotico.jpg",
    },
    {
      id: 6,
      name: "menta",
      img: "/images/materials/genuine_leather/cat2/menta.jpg",
    },
    {
      id: 7,
      name: "miele",
      img: "/images/materials/genuine_leather/cat2/miele.jpg",
    },
    {
      id: 8,
      name: "neve",
      img: "/images/materials/genuine_leather/cat2/neve.jpg",
    },
    {
      id: 9,
      name: "nuvola",
      img: "/images/materials/genuine_leather/cat2/nuvola.jpg",
    },
    {
      id: 10,
      name: "pistaccio",
      img: "/images/materials/genuine_leather/cat2/pistaccio.jpg",
    },
    {
      id: 11,
      name: "ruggine",
      img: "/images/materials/genuine_leather/cat2/ruggine.jpg",
    },
    {
      id: 12,
      name: "sigaro",
      img: "/images/materials/genuine_leather/cat2/sigaro.jpg",
    },
  ],
};

export const Fabrics_Austin: TMaterialGroup = {
  id: 11,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Austin – рогожка с оригинальным, текстурным рисунком поверхности. Ткань сочетает в себе мягкую выразительную фактуру и в то же время высокую износостойкость (более 100 000 циклов), которая позволяет интенсивно использовать материал в жилых и коммерческих проектах. 21 цветовое решение – это яркая комбинация базовых и трендовых тонов.",
  materials: [
    {
      id: 1,
      name: "01-11",
      type: "austin",
      img: "/images/materials/fabrics/austin/01-11.jpg",
    },
    {
      id: 2,
      name: "02-9",
      type: "austin",
      img: "/images/materials/fabrics/austin/02-9.jpg",
    },
    {
      id: 3,
      name: "03-12",
      type: "austin",
      img: "/images/materials/fabrics/austin/03-12.jpg",
    },
    {
      id: 4,
      name: "04-11",
      type: "austin",
      img: "/images/materials/fabrics/austin/04-11.jpg",
    },
    {
      id: 5,
      name: "05-10",
      type: "austin",
      img: "/images/materials/fabrics/austin/05-10.jpg",
    },
    {
      id: 6,
      name: "06-7",
      type: "austin",
      img: "/images/materials/fabrics/austin/06-7.jpg",
    },
    {
      id: 7,
      name: "07-8",
      type: "austin",
      img: "/images/materials/fabrics/austin/07-8.jpg",
    },
    {
      id: 8,
      name: "08-7",
      type: "austin",
      img: "/images/materials/fabrics/austin/08-7.jpg",
    },
    {
      id: 9,
      name: "09-7",
      type: "austin",
      img: "/images/materials/fabrics/austin/09-7.jpg",
    },
    {
      id: 10,
      name: "10-10",
      type: "austin",
      img: "/images/materials/fabrics/austin/10-10.jpg",
    },
    {
      id: 11,
      name: "11-9",
      type: "austin",
      img: "/images/materials/fabrics/austin/11-9.jpg",
    },
    {
      id: 12,
      name: "12-8",
      type: "austin",
      img: "/images/materials/fabrics/austin/12-8.jpg",
    },
    {
      id: 13,
      name: "13-9",
      type: "austin",
      img: "/images/materials/fabrics/austin/13-9.jpg",
    },
    {
      id: 14,
      name: "14-8",
      type: "austin",
      img: "/images/materials/fabrics/austin/14-8.jpg",
    },
    {
      id: 15,
      name: "15-10",
      type: "austin",
      img: "/images/materials/fabrics/austin/15-10.jpg",
    },
    {
      id: 16,
      name: "16-10",
      type: "austin",
      img: "/images/materials/fabrics/austin/16-10.jpg",
    },
    {
      id: 17,
      name: "17-9",
      type: "austin",
      img: "/images/materials/fabrics/austin/17-9.jpg",
    },
    {
      id: 18,
      name: "18-7",
      type: "austin",
      img: "/images/materials/fabrics/austin/18-7.jpg",
    },
    {
      id: 19,
      name: "19-7",
      type: "austin",
      img: "/images/materials/fabrics/austin/19-7.jpg",
    },
    {
      id: 20,
      name: "20-7",
      type: "austin",
      img: "/images/materials/fabrics/austin/20-7.jpg",
    },
    {
      id: 21,
      name: "21-6",
      type: "austin",
      img: "/images/materials/fabrics/austin/21-6.jpg",
    },
  ],
};

export const Fabrics_Clarins: TMaterialGroup = {
  id: 12,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Модная и востребованная буклированная ткань Clarins олицетворяет элегантный стиль в интерьере, создавая воздушные и словно невесомые изделия. Букле преобразует интерьер в статусный, словно именитый модельер поучаствовал в его оформлении. Коллекция иллюстрирует также комфорт уровня hygge: она рождает чувство спокойствия и расслабления, словно оказываешься в комфортном и безопасном месте. Ничто не отвлекает и не раздражает в ней: только гармоничные натуральные тональности, теплота и мягкость фактуры. Неоднородная окраска волокон с отголосками меланжа рисует трехмерный объем: пушистые вкрапления узелков создают тактильно теплую и внешне деликатную поверхность. Небольшая величина узелков коллекции Clarins подойдет большинству мебельных и текстильных проектов. Их небольшой размер максимально универсален.",
  materials: [
    {
      id: 1,
      name: "100",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/100.jpg",
    },
    {
      id: 2,
      name: "130",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/130.jpg",
    },
    {
      id: 3,
      name: "131",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/131.jpg",
    },
    {
      id: 4,
      name: "230",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/230.jpg",
    },
    {
      id: 5,
      name: "235",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/235.jpg",
    },
    {
      id: 6,
      name: "312",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/312.jpg",
    },
    {
      id: 7,
      name: "560",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/560.jpg",
    },
    {
      id: 8,
      name: "690",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/690.jpg",
    },
    {
      id: 9,
      name: "695",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/695.jpg",
    },
    {
      id: 10,
      name: "792",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/792.jpg",
    },
    {
      id: 11,
      name: "900",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/900.jpg",
    },
    {
      id: 12,
      name: "972",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/972.jpg",
    },
    {
      id: 13,
      name: "978",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/978.jpg",
    },
    {
      id: 14,
      name: "995",
      type: "clarins",
      img: "/images/materials/fabrics/clarins/995.jpg",
    },
  ],
};

export const Fabrics_Crown: TMaterialGroup = {
  id: 13,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Crown – велюр с объемным, текстурным рисунком поверхности. Мягкая выразительная фактура создает ощущение уюта и комфорта. Ткани коллекции Crown долговечны, «дышат», не электризуются, гипоаллергенны. Ткани отлично смотрятся на диванах и креслах и придают мебели красивый внешний вид. Европейская цветовая гамма предлагает модные решения для интерьера.",
  materials: [
    {
      id: 1,
      name: "1",
      type: "crown",
      img: "/images/materials/fabrics/crown/1.jpg",
    },
    {
      id: 2,
      name: "2",
      type: "crown",
      img: "/images/materials/fabrics/crown/2.jpg",
    },
    {
      id: 3,
      name: "3",
      type: "crown",
      img: "/images/materials/fabrics/crown/3.jpg",
    },
    {
      id: 4,
      name: "4",
      type: "crown",
      img: "/images/materials/fabrics/crown/4.jpg",
    },
    {
      id: 5,
      name: "5",
      type: "crown",
      img: "/images/materials/fabrics/crown/5.jpg",
    },
    {
      id: 6,
      name: "6",
      type: "crown",
      img: "/images/materials/fabrics/crown/6.jpg",
    },
    {
      id: 7,
      name: "7",
      type: "crown",
      img: "/images/materials/fabrics/crown/7.jpg",
    },
    {
      id: 8,
      name: "8",
      type: "crown",
      img: "/images/materials/fabrics/crown/8.jpg",
    },
    {
      id: 9,
      name: "9",
      type: "crown",
      img: "/images/materials/fabrics/crown/9.jpg",
    },
    {
      id: 10,
      name: "10",
      type: "crown",
      img: "/images/materials/fabrics/crown/10.jpg",
    },
    {
      id: 11,
      name: "11",
      type: "crown",
      img: "/images/materials/fabrics/crown/11.jpg",
    },
    {
      id: 12,
      name: "12",
      type: "crown",
      img: "/images/materials/fabrics/crown/12.jpg",
    },
    {
      id: 13,
      name: "13",
      type: "crown",
      img: "/images/materials/fabrics/crown/13.jpg",
    },
    {
      id: 14,
      name: "14",
      type: "crown",
      img: "/images/materials/fabrics/crown/14.jpg",
    },
    {
      id: 15,
      name: "15",
      type: "crown",
      img: "/images/materials/fabrics/crown/15.jpg",
    },
    {
      id: 16,
      name: "16",
      type: "crown",
      img: "/images/materials/fabrics/crown/16.jpg",
    },
    {
      id: 17,
      name: "17",
      type: "crown",
      img: "/images/materials/fabrics/crown/17.jpg",
    },
    {
      id: 18,
      name: "18",
      type: "crown",
      img: "/images/materials/fabrics/crown/18.jpg",
    },
    {
      id: 19,
      name: "19",
      type: "crown",
      img: "/images/materials/fabrics/crown/19.jpg",
    },
    {
      id: 20,
      name: "20",
      type: "crown",
      img: "/images/materials/fabrics/crown/20.jpg",
    },
  ],
};

export const Fabrics_Laki: TMaterialGroup = {
  id: 14,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Коллекция Laki придется по вкусу любителям и ценителям мягких, объемных, однотонных фактур. Ткань хорошо ложится и на прямые, и на классические формы диванов, подчеркивая красоту их пропорций и деталей. Имеет высокие потребительские и эксплуатационные свойства. В колор-карте коллекции есть как традиционно-классические, так и современные, трендовые цвета.",
  materials: [
    {
      id: 1,
      name: "01-4",
      type: "laki",
      img: "/images/materials/fabrics/laki/01-4.jpg",
    },
    {
      id: 2,
      name: "02-1",
      type: "laki",
      img: "/images/materials/fabrics/laki/02-1.jpg",
    },
    {
      id: 3,
      name: "04-4",
      type: "laki",
      img: "/images/materials/fabrics/laki/04-4.jpg",
    },
    {
      id: 4,
      name: "06-1",
      type: "laki",
      img: "/images/materials/fabrics/laki/06-1.jpg",
    },
    {
      id: 5,
      name: "07-1",
      type: "laki",
      img: "/images/materials/fabrics/laki/07-1.jpg",
    },
    {
      id: 6,
      name: "10-2",
      type: "laki",
      img: "/images/materials/fabrics/laki/10-2.jpg",
    },
    {
      id: 7,
      name: "11-2",
      type: "laki",
      img: "/images/materials/fabrics/laki/11-2.jpg",
    },
    {
      id: 8,
      name: "13-2",
      type: "laki",
      img: "/images/materials/fabrics/laki/13-2.jpg",
    },
    {
      id: 9,
      name: "14-2",
      type: "laki",
      img: "/images/materials/fabrics/laki/14-2.jpg",
    },
    {
      id: 10,
      name: "16-2",
      type: "laki",
      img: "/images/materials/fabrics/laki/16-2.jpg",
    },
    {
      id: 11,
      name: "17-4",
      type: "laki",
      img: "/images/materials/fabrics/laki/17-4.jpg",
    },
    {
      id: 12,
      name: "20-3",
      type: "laki",
      img: "/images/materials/fabrics/laki/20-3.jpg",
    },
    {
      id: 13,
      name: "21-2",
      type: "laki",
      img: "/images/materials/fabrics/laki/21-2.jpg",
    },
    {
      id: 14,
      name: "23-3",
      type: "laki",
      img: "/images/materials/fabrics/laki/23-3.jpg",
    },
    {
      id: 15,
      name: "24-2",
      type: "laki",
      img: "/images/materials/fabrics/laki/24-2.jpg",
    },
    {
      id: 16,
      name: "26-3",
      type: "laki",
      img: "/images/materials/fabrics/laki/26-3.jpg",
    },
    {
      id: 17,
      name: "27-1",
      type: "laki",
      img: "/images/materials/fabrics/laki/27-1.jpg",
    },
    {
      id: 18,
      name: "51-1",
      type: "laki",
      img: "/images/materials/fabrics/laki/51-1.jpg",
    },
  ],
};


export const Fabrics_Missoni: TMaterialGroup = {
  id: 16,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Коллекция Missoni легкая и пластичная, приятная на ощупь -  ворс тоньше либо сравним с шерстью редкой породы монгольских коз. Благородный меланжевый микровелюр, напоминающий теплую и уютную шерсть и кашемир. Меланжевые ткани станут прекрасной основой как для интерьера в классическом стиле, так и скандинавского или минималистического.",
  materials: [
    {
      id: 1,
      name: "01",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/01.jpg",
    },
    {
      id: 2,
      name: "02",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/02.jpg",
    },
    {
      id: 3,
      name: "04",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/04.jpg",
    },
    {
      id: 4,
      name: "05",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/05.jpg",
    },
    {
      id: 5,
      name: "06",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/06.jpg",
    },
    {
      id: 6,
      name: "10",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/10.jpg",
    },
    {
      id: 7,
      name: "11",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/11.jpg",
    },
    {
      id: 8,
      name: "12",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/12.jpg",
    },
    {
      id: 9,
      name: "13",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/13.jpg",
    },
    {
      id: 10,
      name: "14",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/14.jpg",
    },
    {
      id: 11,
      name: "15",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/15.jpg",
    },
    {
      id: 12,
      name: "17",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/17.jpg",
    },
    {
      id: 13,
      name: "18",
      type: "missoni",
      img: "/images/materials/fabrics/missoni/18.jpg",
    },
  ],
};

export const Fabrics_Mys: TMaterialGroup = {
  id: 17,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "MYS – это ненавязчивое стремление к природным мотивам, равновесию и естественному ощущению уюта. Совмещение меланжевых нитей с объёмной фактурой плетения имеет тактильный и визуальный эффект ручной работы, живой вязаной текстуры. Это совместно с палитрой природных оттенков помогает создать органичное пространство для отдыха, восстановления сил и эмоциональной стабильности. Технология Easy Clean обеспечит простой и быстрый уход за тканью.",
  materials: [
    {
      id: 1,
      name: "010",
      type: "mys",
      img: "/images/materials/fabrics/mys/010.jpg",
    },
    {
      id: 2,
      name: "082",
      type: "mys",
      img: "/images/materials/fabrics/mys/082.jpg",
    },
    {
      id: 3,
      name: "560",
      type: "mys",
      img: "/images/materials/fabrics/mys/560.jpg",
    },
    {
      id: 4,
      name: "670",
      type: "mys",
      img: "/images/materials/fabrics/mys/670.jpg",
    },
    {
      id: 5,
      name: "695",
      type: "mys",
      img: "/images/materials/fabrics/mys/695.jpg",
    },
    {
      id: 6,
      name: "788",
      type: "mys",
      img: "/images/materials/fabrics/mys/788.jpg",
    },
    {
      id: 7,
      name: "886",
      type: "mys",
      img: "/images/materials/fabrics/mys/886.jpg",
    },
    {
      id: 8,
      name: "900",
      type: "mys",
      img: "/images/materials/fabrics/mys/900.jpg",
    },
    {
      id: 9,
      name: "912",
      type: "mys",
      img: "/images/materials/fabrics/mys/912.jpg",
    },
    {
      id: 10,
      name: "925",
      type: "mys",
      img: "/images/materials/fabrics/mys/925.jpg",
    },
    {
      id: 11,
      name: "974",
      type: "mys",
      img: "/images/materials/fabrics/mys/974.jpg",
    },
    {
      id: 12,
      name: "995",
      type: "mys",
      img: "/images/materials/fabrics/mys/995.jpg",
    },
    {
      id: 13,
      name: "998",
      type: "mys",
      img: "/images/materials/fabrics/mys/998.jpg",
    },
  ],
};

export const Fabrics_Oscar: TMaterialGroup = {
  id: 18,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "италия, турция",
  description: "Качественные ткани, подобранные специально для наших изделий.",
  materials: [
    {
      id: 1,
      name: "000",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/000.jpg",
    },
    {
      id: 2,
      name: "100",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/100.jpg",
    },
    {
      id: 3,
      name: "122",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/122.jpg",
    },
    {
      id: 4,
      name: "233",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/233.jpg",
    },
    {
      id: 5,
      name: "297",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/297.jpg",
    },
    {
      id: 6,
      name: "338",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/338.jpg",
    },
    {
      id: 7,
      name: "398",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/398.jpg",
    },
    {
      id: 8,
      name: "672",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/672.jpg",
    },
    {
      id: 9,
      name: "696",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/696.jpg",
    },
    {
      id: 10,
      name: "795",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/795.jpg",
    },
    {
      id: 11,
      name: "798",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/798.jpg",
    },
    {
      id: 12,
      name: "960",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/960.jpg",
    },
    {
      id: 13,
      name: "965",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/965.jpg",
    },
    {
      id: 14,
      name: "978",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/978.jpg",
    },
    {
      id: 15,
      name: "990",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/990.jpg",
    },
    {
      id: 16,
      name: "998",
      type: "oscar",
      img: "/images/materials/fabrics/oscar/998.jpg",
    },
  ],
};

export const Fabrics_Trumph: TMaterialGroup = {
  id: 19,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Триумф - коллекция велюра, имеющего благородную матовую поверхность. Мебель из данной ткани выглядит роскошно и прекрасно дополнит любой современный интерьер. Приятная, матовая поверхность навсегда изменит ваше восприятие комфорта, уюта, тепла и функциональности. Повышенная износостойкость и долговечность, устойчивость к загрязнениям и легкость в уходе ставят велюр Триумф в ряд самых востребованных тканей. Благодаря богатой цветовой палитре коллекции вы сможете подобрать идеальное цветовое решение для любого интерьера. Коллекция Триумф - идеальное соотношение цены и качества.",
  materials: [
    {
      id: 1,
      name: "1",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/1.jpg",
    },
    {
      id: 2,
      name: "2",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/2.jpg",
    },
    {
      id: 3,
      name: "3",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/3.jpg",
    },
    {
      id: 4,
      name: "7",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/7.jpg",
    },
    {
      id: 5,
      name: "8",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/8.jpg",
    },
    {
      id: 6,
      name: "9",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/9.jpg",
    },
    {
      id: 7,
      name: "10",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/10.jpg",
    },
    {
      id: 8,
      name: "11",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/11.jpg",
    },
    {
      id: 9,
      name: "12",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/12.jpg",
    },
    {
      id: 10,
      name: "14",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/14.jpg",
    },
    {
      id: 11,
      name: "15",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/15.jpg",
    },
    {
      id: 12,
      name: "16",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/16.jpg",
    },
    {
      id: 13,
      name: "17",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/17.jpg",
    },
    {
      id: 14,
      name: "18",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/18.jpg",
    },
    {
      id: 15,
      name: "19",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/19.jpg",
    },
    {
      id: 16,
      name: "20",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/20.jpg",
    },
    {
      id: 17,
      name: "29",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/29.jpg",
    },
    {
      id: 18,
      name: "30",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/30.jpg",
    },
    {
      id: 19,
      name: "31",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/31.jpg",
    },
    {
      id: 20,
      name: "32",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/32.jpg",
    },
    {
      id: 21,
      name: "33",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/33.jpg",
    },
    {
      id: 22,
      name: "34",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/34.jpg",
    },
    {
      id: 23,
      name: "35",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/35.jpg",
    },
    {
      id: 24,
      name: "36",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/36.jpg",
    },
    {
      id: 25,
      name: "37",
      type: "triumph",
      img: "/images/materials/fabrics/trumph/37.jpg",
    },
  ],
};

export const Fabrics_Wellton: TMaterialGroup = {
  id: 20,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Уютный внешний облик, комфорт от соприкосновения и тактильное тепло рождают по-домашнему притягательный текстиль - рогожку Wellton. Благодаря особому рисунку плетения рогожка выглядит стильно, но в то же время сдержанно и благородно. Выразительная фактура преображает любую форму мягкой мебели. Неоднородная степень меланжевых вкраплений идеально подчеркивает прямые мебельные формы, придает необходимую графичность, при этом сохраняя визуальную мягкость силуэта. Грамотно составленная палитра универсальна: в ней найдется подходящий цвет для любых интерьерных стилей.",
  materials: [
    {
      id: 1,
      name: "000",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/000.jpg",
    },
    {
      id: 2,
      name: "130",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/130.jpg",
    },
    {
      id: 3,
      name: "230",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/230.jpg",
    },
    {
      id: 4,
      name: "297",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/297.jpg",
    },
    {
      id: 5,
      name: "560",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/560.jpg",
    },
    {
      id: 6,
      name: "696",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/696.jpg",
    },
    {
      id: 7,
      name: "697",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/697.jpg",
    },
    {
      id: 8,
      name: "797",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/797.jpg",
    },
    {
      id: 9,
      name: "912",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/912.jpg",
    },
    {
      id: 10,
      name: "953",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/953.jpg",
    },
    {
      id: 11,
      name: "990",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/990.jpg",
    },
    {
      id: 12,
      name: "994",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/994.jpg",
    },
    {
      id: 13,
      name: "998",
      type: "wellton",
      img: "/images/materials/fabrics/wellton/998.jpg",
    },
  ],
};

export const Fabrics_EnjoyLux: TMaterialGroup = {
  id: 23,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Мягкий и уютный шенилл Enjoy с эффектом рогожки, но по тактильным ощущениям превосходит ее в мягкости и бархотистости. Коллекция представлена в 18 оттенках от классической бежево-коричневой и серой гаммы до яркой желто-зеленой и бирюзово-синей гаммы. Коллекция подойдет для  стилей интерьера: скандинавский, классический, романский, конструктизм, хайтек, минимализм.",
  materials: [
    {
      id: 1,
      name: "1",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/1.jpg",
    },
    {
      id: 2,
      name: "2",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/2.jpg",
    },
    {
      id: 3,
      name: "3",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/3.jpg",
    },
    {
      id: 4,
      name: "4",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/4.jpg",
    },
    {
      id: 5,
      name: "10",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/10.jpg",
    },
    {
      id: 6,
      name: "11",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/11.jpg",
    },
    {
      id: 7,
      name: "12",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/12.jpg",
    },
    {
      id: 8,
      name: "13",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/13.jpg",
    },
    {
      id: 9,
      name: "14",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/14.jpg",
    },
    {
      id: 10,
      name: "15",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/15.jpg",
    },
    {
      id: 11,
      name: "17",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/17.jpg",
    },
    {
      id: 12,
      name: "18",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/18.jpg",
    },
    {
      id: 13,
      name: "19",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/19.jpg",
    },
    {
      id: 14,
      name: "20",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/20.jpg",
    },
    {
      id: 15,
      name: "21",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/21.jpg",
    },
    {
      id: 16,
      name: "23",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/23.jpg",
    },
    {
      id: 17,
      name: "24",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/24.jpg",
    },
    {
      id: 18,
      name: "22",
      type: "enjoy lux",
      img: "/images/materials/fabrics/enjoy_lux/22.jpg",
    },
  ],
};
export const Fabrics_Jazz: TMaterialGroup = {
  id: 25,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description: "Рогожка Jazz подходит для интерьеров любых стилей и направлений. Актуальная фактура выгодно подчеркнет все особенности мебели, а широкая палитра придаст настроение жилому пространству. Износостойкость для такого вида материалов значительно выше нормы - более 45 000 циклов по Мартиндейлу.",
  materials: [
    {
      id: 1,
      name: "01",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/01.jpg",
    },
    {
      id: 2,
      name: "02",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/02.jpg",
    },
    {
      id: 3,
      name: "07",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/07.jpg",
    },
    {
      id: 4,
      name: "04",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/04.jpg",
    },
    {
      id: 5,
      name: "05",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/05.jpg",
    },
    {
      id: 6,
      name: "06",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/06.jpg",
    },
    {
      id: 7,
      name: "08",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/08.jpg",
    },
    {
      id: 8,
      name: "09",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/09.jpg",
    },
    {
      id: 9,
      name: "10",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/10.jpg",
    },
    {
      id: 10,
      name: "11",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/11.jpg",
    },
    {
      id: 11,
      name: "12",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/12.jpg",
    },
    {
      id: 12,
      name: "13",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/13.jpg",
    },
    {
      id: 13,
      name: "14",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/14.jpg",
    },
    {
      id: 14,
      name: "15",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/15.jpg",
    },
    {
      id: 15,
      name: "16",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/16.jpg",
    },
    {
      id: 16,
      name: "17",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/17.jpg",
    },
    {
      id: 17,
      name: "19",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/19.jpg",
    },
    {
      id: 18,
      name: "20",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/20.jpg",
    },
    {
      id: 19,
      name: "21",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/21.jpg",
    },
    {
      id: 20,
      name: "18",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/18.jpg",
    },
    {
      id: 21,
      name: "22",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/22.jpg",
    },
    {
      id: 22,
      name: "23",
      type: "jazz",
      img: "/images/materials/fabrics/jazz/23.jpg",
    },
  ],
};

export const Fabrics_Luna: TMaterialGroup = {
  id: 26,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description: "Выразительная текстура, высокая технологичность и износостойкость: все это - ткань новой коллекции Luna. Она станет безупречным дополнением любого интерьера, благодаря разнообразию цветовой гаммы.",
  materials: [
    {
      id: 1,
      name: "01",
      type: "luna",
      img: "/images/materials/fabrics/luna/01.jpg",
    },
    {
      id: 2,
      name: "12",
      type: "luna",
      img: "/images/materials/fabrics/luna/12.jpg",
    },
    {
      id: 3,
      name: "14",
      type: "luna",
      img: "/images/materials/fabrics/luna/14.jpg",
    },
    {
      id: 4,
      name: "15",
      type: "luna",
      img: "/images/materials/fabrics/luna/15.jpg",
    },
    {
      id: 5,
      name: "16",
      type: "luna",
      img: "/images/materials/fabrics/luna/16.jpg",
    },
    {
      id: 6,
      name: "24",
      type: "luna",
      img: "/images/materials/fabrics/luna/24.jpg",
    },
    {
      id: 7,
      name: "27",
      type: "luna",
      img: "/images/materials/fabrics/luna/27.jpg",
    },
    {
      id: 8,
      name: "29",
      type: "luna",
      img: "/images/materials/fabrics/luna/29.jpg",
    },
    {
      id: 9,
      name: "30",
      type: "luna",
      img: "/images/materials/fabrics/luna/30.jpg",
    },
    {
      id: 10,
      name: "32",
      type: "luna",
      img: "/images/materials/fabrics/luna/32.jpg",
    },
    {
      id: 11,
      name: "33",
      type: "luna",
      img: "/images/materials/fabrics/luna/33.jpg",
    },
    {
      id: 12,
      name: "34",
      type: "luna",
      img: "/images/materials/fabrics/luna/34.jpg",
    },
    {
      id: 13,
      name: "35",
      type: "luna",
      img: "/images/materials/fabrics/luna/35.jpg",
    },
    {
      id: 14,
      name: "60",
      type: "luna",
      img: "/images/materials/fabrics/luna/60.jpg",
    },
    {
      id: 15,
      name: "65",
      type: "luna",
      img: "/images/materials/fabrics/luna/65.jpg",
    },
    {
      id: 16,
      name: "85",
      type: "luna",
      img: "/images/materials/fabrics/luna/85.jpg",
    },
    {
      id: 17,
      name: "96",
      type: "luna",
      img: "/images/materials/fabrics/luna/96.jpg",
    },
    {
      id: 18,
      name: "21",
      type: "luna",
      img: "/images/materials/fabrics/luna/21.jpg",
    },
  ],
};

export const Fabrics_Marin: TMaterialGroup = {
  id: 27,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description: "Marin - мягкий фактурный велюр, дарящий тепло и тактильный релакс. Широкая цветовая палитра, благородный внешний вид и практичность в использовании помогают сделать однозначный выбор в пользу данной коллекции.",
  materials: [
    {
      id: 1,
      name: "01",
      type: "marin",
      img: "/images/materials/fabrics/marin/01.jpg",
    },
    {
      id: 2,
      name: "02",
      type: "marin",
      img: "/images/materials/fabrics/marin/02.jpg",
    },
    {
      id: 3,
      name: "03",
      type: "marin",
      img: "/images/materials/fabrics/marin/03.jpg",
    },
    {
      id: 4,
      name: "04",
      type: "marin",
      img: "/images/materials/fabrics/marin/04.jpg",
    },
    {
      id: 5,
      name: "05",
      type: "marin",
      img: "/images/materials/fabrics/marin/05.jpg",
    },
    {
      id: 6,
      name: "06",
      type: "marin",
      img: "/images/materials/fabrics/marin/06.jpg",
    },
    {
      id: 7,
      name: "08",
      type: "marin",
      img: "/images/materials/fabrics/marin/08.jpg",
    },
    {
      id: 8,
      name: "09",
      type: "marin",
      img: "/images/materials/fabrics/marin/09.jpg",
    },
    {
      id: 9,
      name: "10",
      type: "marin",
      img: "/images/materials/fabrics/marin/10.jpg",
    },
    {
      id: 10,
      name: "11",
      type: "marin",
      img: "/images/materials/fabrics/marin/11.jpg",
    },
    {
      id: 11,
      name: "12",
      type: "marin",
      img: "/images/materials/fabrics/marin/12.jpg",
    },
    {
      id: 12,
      name: "13",
      type: "marin",
      img: "/images/materials/fabrics/marin/13.jpg",
    },
    {
      id: 13,
      name: "14",
      type: "marin",
      img: "/images/materials/fabrics/marin/14.jpg",
    },
    {
      id: 14,
      name: "15",
      type: "marin",
      img: "/images/materials/fabrics/marin/15.jpg",
    },
    {
      id: 15,
      name: "16",
      type: "marin",
      img: "/images/materials/fabrics/marin/16.jpg",
    },
    {
      id: 16,
      name: "17",
      type: "marin",
      img: "/images/materials/fabrics/marin/17.jpg",
    },
    {
      id: 17,
      name: "19",
      type: "marin",
      img: "/images/materials/fabrics/marin/19.jpg",
    },
    {
      id: 18,
      name: "20",
      type: "marin",
      img: "/images/materials/fabrics/marin/20.jpg",
    },
    {
      id: 19,
      name: "21",
      type: "marin",
      img: "/images/materials/fabrics/marin/21.jpg",
    },
    {
      id: 20,
      name: "18",
      type: "marin",
      img: "/images/materials/fabrics/marin/18.jpg",
    },
    {
      id: 21,
      name: "07",
      type: "marin",
      img: "/images/materials/fabrics/marin/07.jpg",
    },
  ],
};

export const Fabrics_Matrix: TMaterialGroup = {
  id: 28,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description:
    "Тактильное тепло рогожки Matrix создают уют в доме. Благодаря особому рисунку плетения Matrix выглядит стильно, но в тоже время стильно и благородно. Выразительная фактура ткани, преображает любую форму мягкой мебели, приает необходимую графичность, при этом сохраняя визуальную мягкость силуэта. Грамотно составленная политра универсальна: в ней найдется подходящий цвет для любых стилей.",
  materials: [
    {
      id: 1,
      name: "01",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/01.jpg",
    },
    {
      id: 2,
      name: "02",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/02.jpg",
    },
    {
      id: 3,
      name: "04",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/04.jpg",
    },
    {
      id: 4,
      name: "05",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/05.jpg",
    },
    {
      id: 5,
      name: "07",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/07.jpg",
    },
    {
      id: 6,
      name: "09",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/09.jpg",
    },
    {
      id: 7,
      name: "10",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/10.jpg",
    },
    {
      id: 8,
      name: "11",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/11.jpg",
    },
    {
      id: 9,
      name: "12",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/12.jpg",
    },
    {
      id: 10,
      name: "13",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/13.jpg",
    },
    {
      id: 11,
      name: "14",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/14.jpg",
    },
    {
      id: 12,
      name: "15",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/15.jpg",
    },
    {
      id: 13,
      name: "16",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/16.jpg",
    },
    {
      id: 14,
      name: "18",
      type: "matrix",
      img: "/images/materials/fabrics/matrix/18.jpg",
    },
  ],
};

export const Fabrics_Rio: TMaterialGroup = {
  id: 29,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description: "Изящество и чувство стиля слединяются в коллекции велюров Rio. Меланжевая фактура, глубокие насыщенные цвета и тактильные ощущения шелка подчеркивают изысканность материала. Мебель из коллекции велюров Rio станет настоящим украшением Вашего дома. А благодаря превосходным эксплуатационным характеристикам интерьер будет радовать вас долгие годы.",
  materials: [
    {
      id: 1,
      name: "1",
      type: "rio",
      img: "/images/materials/fabrics/rio/1.jpg",
    },
    {
      id: 2,
      name: "2",
      type: "rio",
      img: "/images/materials/fabrics/rio/2.jpg",
    },
    {
      id: 3,
      name: "3",
      type: "rio",
      img: "/images/materials/fabrics/rio/3.jpg",
    },
    {
      id: 4,
      name: "4",
      type: "rio",
      img: "/images/materials/fabrics/rio/4.jpg",
    },
    {
      id: 5,
      name: "5",
      type: "rio",
      img: "/images/materials/fabrics/rio/5.jpg",
    },
    {
      id: 6,
      name: "6",
      type: "rio",
      img: "/images/materials/fabrics/rio/6.jpg",
    },
    {
      id: 7,
      name: "7",
      type: "rio",
      img: "/images/materials/fabrics/rio/7.jpg",
    },
    {
      id: 8,
      name: "8",
      type: "rio",
      img: "/images/materials/fabrics/rio/8.jpg",
    },
    {
      id: 9,
      name: "9",
      type: "rio",
      img: "/images/materials/fabrics/rio/9.jpg",
    },
    {
      id: 10,
      name: "10",
      type: "rio",
      img: "/images/materials/fabrics/rio/10.jpg",
    },
    {
      id: 11,
      name: "11",
      type: "rio",
      img: "/images/materials/fabrics/rio/11.jpg",
    },
    {
      id: 12,
      name: "12",
      type: "rio",
      img: "/images/materials/fabrics/rio/12.jpg",
    },
    {
      id: 13,
      name: "13",
      type: "rio",
      img: "/images/materials/fabrics/rio/13.jpg",
    },
    {
      id: 14,
      name: "14",
      type: "rio",
      img: "/images/materials/fabrics/rio/14.jpg",
    },
    {
      id: 15,
      name: "15",
      type: "rio",
      img: "/images/materials/fabrics/rio/15.jpg",
    },
    {
      id: 16,
      name: "16",
      type: "rio",
      img: "/images/materials/fabrics/rio/16.jpg",
    },
  ],
};

export const Fabrics_Nola: TMaterialGroup = {
  id: 37,
  title: "ткань категория 1",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "китай",
  description: "Это современная переосмысленная версия классической мебельной рогожки, где традиции и новаторство встречаются во впечатляющем синтезе. Захватывающий элемент дизайна Nola – это ее фантазийная, трехцветная нить. Переплетение этих нитей на лицевой части создает необычный узор, напоминающий крестик, что качественно выделяет ее среди аналогичных коллекций представленных сегодня на рынке, потому что классическая рогожка всегда имеет привычный шахматный рисунок. Этот уникальный узор и делает коллекцию Nola современным произведением искусства.",
  materials: [
    {
      id: 1,
      name: "001",
      type: "nola",
      img: "/images/materials/fabrics/nola/001.jpg",
    },
    {
      id: 2,
      name: "004",
      type: "nola",
      img: "/images/materials/fabrics/nola/004.jpg",
    },
    {
      id: 3,
      name: "005",
      type: "nola",
      img: "/images/materials/fabrics/nola/005.jpg",
    },
    {
      id: 4,
      name: "006",
      type: "nola",
      img: "/images/materials/fabrics/nola/006.jpg",
    },
    {
      id: 5,
      name: "007",
      type: "nola",
      img: "/images/materials/fabrics/nola/007.jpg",
    },
    {
      id: 6,
      name: "008",
      type: "nola",
      img: "/images/materials/fabrics/nola/008.jpg",
    },
    {
      id: 7,
      name: "009",
      type: "nola",
      img: "/images/materials/fabrics/nola/009.jpg",
    },
    {
      id: 8,
      name: "010",
      type: "nola",
      img: "/images/materials/fabrics/nola/010.jpg",
    },
    {
      id: 9,
      name: "012",
      type: "nola",
      img: "/images/materials/fabrics/nola/012.jpg",
    },
    {
      id: 10,
      name: "014",
      type: "nola",
      img: "/images/materials/fabrics/nola/014.jpg",
    },
    {
      id: 11,
      name: "015",
      type: "nola",
      img: "/images/materials/fabrics/nola/015.jpg",
    },
    {
      id: 12,
      name: "016",
      type: "nola",
      img: "/images/materials/fabrics/nola/016.jpg",
    },
    {
      id: 13,
      name: "017",
      type: "nola",
      img: "/images/materials/fabrics/nola/017.jpg",
    },
  ],
};

export const Fabrics_Lanvin: TMaterialGroup = {
  id: 15,
  title: "ткань категория 2",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "турция",
  description:
    "Коллекция Lanvin выглядит нарочито грубой, но при этом обладает объёмной формой с приятной мягкостью и теплом. Палитра ориентирована на респектабельные современные интерьеры, где используется дерево ценных пород, мрамор, полированная сталь или латунь в качестве отделочных материалов. Большое количество петель, так называемая «шершавость» поверхности, плотно сидят в структуре ткани: не выдергиваются и не образуют затяжек. Благодаря своей объемной фактуре букле скрывает дефекты и скрадывает неровности швов. Полиэстер в составе нити придаёт ей прочность и устойчивость к разрывам, а вискоза позволяет воздуху циркулировать среди волокон.",
  materials: [
    {
      id: 1,
      name: "000",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/000.jpg",
    },
    {
      id: 2,
      name: "010",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/010.jpg",
    },
    {
      id: 3,
      name: "130",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/130.jpg",
    },
    {
      id: 4,
      name: "225",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/225.jpg",
    },
    {
      id: 5,
      name: "233",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/233.jpg",
    },
    {
      id: 6,
      name: "497",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/497.jpg",
    },
    {
      id: 7,
      name: "618",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/618.jpg",
    },
    {
      id: 8,
      name: "790",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/790.jpg",
    },
    {
      id: 9,
      name: "795",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/795.jpg",
    },
    {
      id: 10,
      name: "797",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/797.jpg",
    },
    {
      id: 11,
      name: "902",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/902.jpg",
    },
    {
      id: 12,
      name: "924",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/924.jpg",
    },
    {
      id: 13,
      name: "997",
      type: "lanvin",
      img: "/images/materials/fabrics/lanvin/997.jpg",
    },
  ],
};

export const Fabrics_Luca: TMaterialGroup = {
  id: 31,
  title: "ткань категория 3",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "турция",
  description: "Мебельная ткань рогожка Luca – это выразительная и стильная ткань для обивки мебели. Более 30 оттенков позволяют выбрать цвет, который подходит именно вам. В составе этой ткани присутствует хлопок, что делает ее мягкой и комфортной при использовании. Удивительная сочетаемость различных оттенков позволяет создавать привлекательный дизайн мебели, которая не только красива, но и удобна в использовании.",
  materials: [
    {
      id: 1,
      name: "02",
      type: "luca",
      img: "/images/materials/fabrics/luca/02.jpg",
    },
    {
      id: 2,
      name: "04",
      type: "luca",
      img: "/images/materials/fabrics/luca/04.jpg",
    },
    {
      id: 3,
      name: "08",
      type: "luca",
      img: "/images/materials/fabrics/luca/08.jpg",
    },
    {
      id: 4,
      name: "14",
      type: "luca",
      img: "/images/materials/fabrics/luca/14.jpg",
    },
    {
      id: 5,
      name: "16",
      type: "luca",
      img: "/images/materials/fabrics/luca/16.jpg",
    },
    {
      id: 6,
      name: "17",
      type: "luca",
      img: "/images/materials/fabrics/luca/17.jpg",
    },
    {
      id: 7,
      name: "24",
      type: "luca",
      img: "/images/materials/fabrics/luca/24.jpg",
    },
    {
      id: 8,
      name: "26",
      type: "luca",
      img: "/images/materials/fabrics/luca/26.jpg",
    },
    {
      id: 9,
      name: "27",
      type: "luca",
      img: "/images/materials/fabrics/luca/27.jpg",
    },
    {
      id: 10,
      name: "34",
      type: "luca",
      img: "/images/materials/fabrics/luca/34.jpg",
    },
    {
      id: 11,
      name: "37",
      type: "luca",
      img: "/images/materials/fabrics/luca/37.jpg",
    },
    {
      id: 12,
      name: "38",
      type: "luca",
      img: "/images/materials/fabrics/luca/38.jpg",
    },
    {
      id: 13,
      name: "39",
      type: "luca",
      img: "/images/materials/fabrics/luca/39.jpg",
    },
    {
      id: 14,
      name: "44",
      type: "luca",
      img: "/images/materials/fabrics/luca/44.jpg",
    },
    {
      id: 15,
      name: "47",
      type: "luca",
      img: "/images/materials/fabrics/luca/47.jpg",
    },
    {
      id: 16,
      name: "48",
      type: "luca",
      img: "/images/materials/fabrics/luca/48.jpg",
    },
    {
      id: 17,
      name: "49",
      type: "luca",
      img: "/images/materials/fabrics/luca/49.jpg",
    },
    {
      id: 18,
      name: "53",
      type: "luca",
      img: "/images/materials/fabrics/luca/53.jpg",
    },
    {
      id: 19,
      name: "56",
      type: "luca",
      img: "/images/materials/fabrics/luca/56.jpg",
    },
    {
      id: 20,
      name: "58",
      type: "luca",
      img: "/images/materials/fabrics/luca/58.jpg",
    },
    {
      id: 21,
      name: "59",
      type: "luca",
      img: "/images/materials/fabrics/luca/59.jpg",
    },
    {
      id: 22,
      name: "63",
      type: "luca",
      img: "/images/materials/fabrics/luca/63.jpg",
    },
    {
      id: 23,
      name: "66",
      type: "luca",
      img: "/images/materials/fabrics/luca/66.jpg",
    },
  ],
};

export const Fabrics_Puffy: TMaterialGroup = {
  id: 32,
  title: "ткань категория 3",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "турция",
  description: "Efendi Puffy – это мебельная шенилл ткань с высокой износостойкостью и водоотталкивающими свойствами. Она доступна в 21 спокойном и нежном оттенке, что позволяет подобрать ее под любой интерьер. Пропитка также делает ее устойчивой к пыли и загрязнениям. Мебельные изделия из данной ткани будут служить долго и сохранят свой оригинальный вид.",
  materials: [
    {
      id: 1,
      name: "00",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/00.jpg",
    },
    {
      id: 2,
      name: "04",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/04.jpg",
    },
    {
      id: 3,
      name: "06",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/06.jpg",
    },
    {
      id: 4,
      name: "14",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/14.jpg",
    },
    {
      id: 5,
      name: "16",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/16.jpg",
    },
    {
      id: 6,
      name: "17",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/17.jpg",
    },
    {
      id: 7,
      name: "18",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/18.jpg",
    },
    {
      id: 8,
      name: "24",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/24.jpg",
    },
    {
      id: 9,
      name: "26",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/26.jpg",
    },
    {
      id: 10,
      name: "27",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/27.jpg",
    },
    {
      id: 11,
      name: "28",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/28.jpg",
    },
    {
      id: 12,
      name: "29",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/29.jpg",
    },
    {
      id: 13,
      name: "37",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/37.jpg",
    },
    {
      id: 14,
      name: "38",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/38.jpg",
    },
    {
      id: 15,
      name: "39",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/39.jpg",
    },
    {
      id: 16,
      name: "47",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/47.jpg",
    },
    {
      id: 17,
      name: "48",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/48.jpg",
    },
    {
      id: 18,
      name: "49",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/49.jpg",
    },
    {
      id: 19,
      name: "66",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/66.jpg",
    },
    {
      id: 20,
      name: "74",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/74.jpg",
    },
    {
      id: 21,
      name: "76",
      type: "puffy",
      img: "/images/materials/fabrics/puffy/76.jpg",
    },
  ],
};

export const Fabrics_Retro: TMaterialGroup = {
  id: 33,
  title: "ткань категория 3",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "турция",
  description: "Качественные ткани, подобранные специально для наших изделий.",
  materials: [
    {
      id: 1,
      name: "00",
      type: "retro",
      img: "/images/materials/fabrics/retro/00.jpg",
    },
    {
      id: 2,
      name: "04",
      type: "retro",
      img: "/images/materials/fabrics/retro/04.jpg",
    },
    {
      id: 3,
      name: "06",
      type: "retro",
      img: "/images/materials/fabrics/retro/06.jpg",
    },
    {
      id: 4,
      name: "14",
      type: "retro",
      img: "/images/materials/fabrics/retro/14.jpg",
    },
    {
      id: 5,
      name: "16",
      type: "retro",
      img: "/images/materials/fabrics/retro/16.jpg",
    },
    {
      id: 6,
      name: "17",
      type: "retro",
      img: "/images/materials/fabrics/retro/17.jpg",
    },
    {
      id: 7,
      name: "24",
      type: "retro",
      img: "/images/materials/fabrics/retro/24.jpg",
    },
    {
      id: 8,
      name: "26",
      type: "retro",
      img: "/images/materials/fabrics/retro/26.jpg",
    },
    {
      id: 9,
      name: "27",
      type: "retro",
      img: "/images/materials/fabrics/retro/27.jpg",
    },
    {
      id: 10,
      name: "37",
      type: "retro",
      img: "/images/materials/fabrics/retro/37.jpg",
    },
    {
      id: 11,
      name: "39",
      type: "retro",
      img: "/images/materials/fabrics/retro/39.jpg",
    },
    {
      id: 12,
      name: "44",
      type: "retro",
      img: "/images/materials/fabrics/retro/44.jpg",
    },
    {
      id: 13,
      name: "45",
      type: "retro",
      img: "/images/materials/fabrics/retro/45.jpg",
    },
    {
      id: 14,
      name: "47",
      type: "retro",
      img: "/images/materials/fabrics/retro/47.jpg",
    },
    {
      id: 15,
      name: "48",
      type: "retro",
      img: "/images/materials/fabrics/retro/48.jpg",
    },
    {
      id: 16,
      name: "49",
      type: "retro",
      img: "/images/materials/fabrics/retro/49.jpg",
    },
    {
      id: 17,
      name: "54",
      type: "retro",
      img: "/images/materials/fabrics/retro/54.jpg",
    },
    {
      id: 18,
      name: "56",
      type: "retro",
      img: "/images/materials/fabrics/retro/56.jpg",
    },
    {
      id: 19,
      name: "66",
      type: "retro",
      img: "/images/materials/fabrics/retro/66.jpg",
    },
    {
      id: 20,
      name: "76",
      type: "retro",
      img: "/images/materials/fabrics/retro/76.jpg",
    },
    {
      id: 21,
      name: "86",
      type: "retro",
      img: "/images/materials/fabrics/retro/86.jpg",
    },
  ],
};

export const Fabrics_Talia: TMaterialGroup = {
  id: 35,
  title: "ткань категория 2",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "турция",
  description: "Качественные ткани, подобранные специально для наших изделий.",
  materials: [
    {
      id: 1,
      name: "02",
      type: "talia",
      img: "/images/materials/fabrics/talia/02.jpg",
    },
    {
      id: 2,
      name: "04",
      type: "talia",
      img: "/images/materials/fabrics/talia/04.jpg",
    },
    {
      id: 3,
      name: "14",
      type: "talia",
      img: "/images/materials/fabrics/talia/14.jpg",
    },
    {
      id: 4,
      name: "24",
      type: "talia",
      img: "/images/materials/fabrics/talia/24.jpg",
    },
    {
      id: 5,
      name: "26",
      type: "talia",
      img: "/images/materials/fabrics/talia/26.jpg",
    },
    {
      id: 6,
      name: "34",
      type: "talia",
      img: "/images/materials/fabrics/talia/34.jpg",
    },
    {
      id: 7,
      name: "37",
      type: "talia",
      img: "/images/materials/fabrics/talia/37.jpg",
    },
    {
      id: 8,
      name: "44",
      type: "talia",
      img: "/images/materials/fabrics/talia/44.jpg",
    },
    {
      id: 9,
      name: "49",
      type: "talia",
      img: "/images/materials/fabrics/talia/49.jpg",
    },
    {
      id: 10,
      name: "56",
      type: "talia",
      img: "/images/materials/fabrics/talia/56.jpg",
    },
  ],
};

export const Fabrics_Teddy: TMaterialGroup = {
  id: 36,
  title: "ткань категория 3",
  furnish: "ткани",
  base: "",
  hem: "",
  manufacturer: "турция",
  description: "Мебельная ткань букле Teddy – идеальное решение для создания уютной атмосферы в доме. Эта мягкая ткань ворсистая и очень приятная на ощупь, а также имеет большой выбор цвета. Она подходит для мебели премиум сегмента, которая будет радовать глаз и приносить комфорт. Очень уютная и приятная, ткань Teddy станет идеальным выбором для тех, кто ценит качество и стиль в дизайне интерьера.",
  materials: [
    {
      id: 1,
      name: "00",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/00.jpg",
    },
    {
      id: 2,
      name: "02",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/02.jpg",
    },
    {
      id: 3,
      name: "04",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/04.jpg",
    },
    {
      id: 4,
      name: "14",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/14.jpg",
    },
    {
      id: 5,
      name: "16",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/16.jpg",
    },
    {
      id: 6,
      name: "24",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/24.jpg",
    },
    {
      id: 7,
      name: "26",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/26.jpg",
    },
    {
      id: 8,
      name: "27",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/27.jpg",
    },
    {
      id: 9,
      name: "29",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/29.jpg",
    },
    {
      id: 10,
      name: "33",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/33.jpg",
    },
    {
      id: 11,
      name: "34",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/34.jpg",
    },
    {
      id: 12,
      name: "35",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/35.jpg",
    },
    {
      id: 13,
      name: "37",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/37.jpg",
    },
    {
      id: 14,
      name: "38",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/38.jpg",
    },
    {
      id: 15,
      name: "44",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/44.jpg",
    },
    {
      id: 16,
      name: "45",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/45.jpg",
    },
    {
      id: 17,
      name: "48",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/48.jpg",
    },
    {
      id: 18,
      name: "54",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/54.jpg",
    },
    {
      id: 19,
      name: "56",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/56.jpg",
    },
    {
      id: 20,
      name: "58",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/58.jpg",
    },
    {
      id: 21,
      name: "59",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/59.jpg",
    },
    {
      id: 22,
      name: "76",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/76.jpg",
    },
    {
      id: 23,
      name: "89",
      type: "teddy",
      img: "/images/materials/fabrics/teddy/89.jpg",
    },
  ],
};

export const Steal: TMaterialGroup = {
  id: 37,
  title: "нержавеющая сталь",
  furnish: "нержавеющая сталь",
  base: "",
  hem: "",
  manufacturer: "Россия",
  description: "Нержавеющая сталь прочна, отличается долгим сроком службы и красивым видом. Нержавейка устойчива к окислению при высоких температурах, не подвержена влиянию атмосферных явлений, влажности, может использоваться в агрессивных условиях без дополнительного защитного покрытия. На это, а также на сложность производства влияют содержание металлов и другие данные.",
  materials: [
    {
      id: 1,
      name: "steel",
      img: "/images/materials/steal/nerj.jpg",
    }
  ],
}

export const allMaterials = [
  Architectural_concrete,
  Ceramics,
  Enamel,
  EnamelWithOakTexture,
  Fabrics_Austin,
  Fabrics_Clarins,
  Fabrics_Crown,
  Fabrics_EnjoyLux,
  Fabrics_Jazz,
  Fabrics_Laki,
  Fabrics_Lanvin,
  Fabrics_Luca,
  Fabrics_Luna,
  Fabrics_Marin,
  Fabrics_Matrix,
  Fabrics_Missoni,
  Fabrics_Mys,
  Fabrics_Nola,
  Fabrics_Oscar,
  Fabrics_Puffy,
  Fabrics_Retro,
  Fabrics_Rio,
  Fabrics_Talia,
  Fabrics_Teddy,
  Fabrics_Trumph,
  Fabrics_Wellton,
  FenixNTM,
  HPL,
  Leather_cat1,
  Leather_cat2,
  Metal,
  Metallic,
  Oak_tinting,
  Steal,
];

export const allFabrics = [
  Fabrics_Austin,
  Fabrics_Clarins,
  Fabrics_Crown,
  Fabrics_Laki,
  Fabrics_Lanvin,
  Fabrics_Missoni,
  Fabrics_Mys,
  Fabrics_Oscar,
  Fabrics_Trumph,
  Fabrics_Wellton,
  Fabrics_EnjoyLux,
  Fabrics_Jazz,
  Fabrics_Luna,
  Fabrics_Marin,
  Fabrics_Matrix,
  Fabrics_Rio,
  Fabrics_Luca,
  Fabrics_Puffy,
  Fabrics_Retro,
  Fabrics_Talia,
  Fabrics_Teddy,
  Fabrics_Nola,
];
