export const altay = {
  id: 1,
  title: "altay",
  modelsSlider: [
    "/images/products/altay/models/1.jpg",
    "/images/products/altay/models/2.jpg",
    "/images/products/altay/models/3.jpg",
    "/images/products/altay/models/4.jpg",
    "/images/products/altay/models/5.jpg",
    "/images/products/altay/models/6.jpg",
    "/images/products/altay/models/7.jpg",
    "/images/products/altay/models/8.jpg",
    "/images/products/altay/models/9.jpg",
    "/images/products/altay/models/10.jpg",
    "/images/products/altay/models/11.jpg",
    "/images/products/altay/models/12.jpg",
    "/images/products/altay/models/13.jpg",
    "/images/products/altay/models/14.jpg",
    "/images/products/altay/models/15.jpg",
    "/images/products/altay/models/16.jpg",
    "/images/products/altay/models/17.jpg",
    "/images/products/altay/models/18.jpg",
    "/images/products/altay/models/19.jpg",
    "/images/products/altay/models/20.jpg",
    "/images/products/altay/models/21.jpg",
    "/images/products/altay/models/22.jpg",
    "/images/products/altay/models/23.jpg",
    "/images/products/altay/models/24.jpg",
    "/images/products/altay/models/25.jpg",
    "/images/products/altay/models/26.jpg",
    "/images/products/altay/models/27.jpg",
    "/images/products/altay/models/28.jpg",
    "/images/products/altay/models/29.jpg",
    "/images/products/altay/models/30.jpg",
  ],
  description:
    "Стол «Алтай»  обладает классической формой, которая гармонично сочетает в себе широкую гамму материалов. Данная модель стола конструктивно может быть изготовлена в двух вариантах: раздвижной и нераздвижной. Стол раскладывается из круга в овал.  Отделка столешницы может быть выполнена из шпона дуба, нанопластика FENIX NTM, hpl пластика 'под мрамор'. Основание подстолья облицовано пластиной из нержавеющей стали с отделкой «сатин».  Складной механизм прост в эксплуатации, подойдёт для ежедневного использования. Сам механизм полностью скрыт царгой, как в сложенном, так и разложенном виде.   Нога подстолья и пояс вокруг столешницы имеют два варианта отделки: натуральная кожа или шпон дуба.  Кожаные элементы имеют декоративную отстрочку, придающую изделию особый шик и индивидуальность!",
  designer: "Сергей Беляков",
  dateOfCreation: 2021,
  countertop: ["hpl / fenix ntm", "шпон дуба", "керамика"],
  underframe: ["натуральная кожа / сталь", "шпон дуба / сталь"],
  sizesSlider: ["/images/products/altay/sizes/1.jpg"],
  visualisations: [
    "/images/products/altay/interior/1.jpg",
    "/images/products/altay/interior/2.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/altay/projects/1.jpg",
    },
    {
      img: "/images/products/altay/projects/2.jpg",
    },
    {
      img: "/images/products/altay/projects/3.jpg",
    },
    {
      img: "/images/products/altay/projects/4.jpg",
    },
  ],
  price: [154700],
  params: {
    "шпон дуба / сталь": {
      "hpl / fenix ntm": {
        "1100 Х 750": 171500,
        "1100 / 1515 Х 750": 237000,
        "1270 Х 750": 185000,
        "1270 / 1720 Х 750": 261400,
      },
      "шпон дуба": {
        "1100 Х 750": 154700,
        "1100 / 1515 Х 750": 232800,
        "1270 Х 750": 166200,
        "1270 / 1720 Х 750": 248300,
      },
      "керамика": {
        "1100 / 1515 Х 750": 272200,
        "1270 / 1720 Х 750": 287600,
      },
    },
    "кожа / сталь": {
      "hpl / fenix ntm": {
        "1100 Х 750": 177700,
        "1100 / 1515 Х 750": 246600,
        "1270 Х 750": 192700,
        "1270 / 1720 Х 750": 271300,
      },
      "шпон дуба": {
        "1100 Х 750": 170500,
        "1100 / 1515 Х 750": 242400,
        "1270 Х 750": 184200,
        "1270 / 1720 Х 750": 257900,
      },
      "керамика": {
        "1100 / 1515 Х 750": 281800,
        "1270 / 1720 Х 750": 297200,
      },
    },
  },
  category: "TABLE_CIRCLE TABLE_SLIDING",
  name: "алтай / алтай раздвижной",
  previewImg: "/images/products/altay/preview.jpg",
  position: 6,
  sortedPosition: 4,
  mobilePosition: 13,
  model: "https://disk.yandex.ru/d/HDfsYIzINb6g7g",
  tags: ["стол", "круглый", "раздвижной"],
};
