export const baikal = {
  id: 2,
  title: "baikal",
  modelsSlider: [
    "/images/products/baikal/models/1.jpg",
    "/images/products/baikal/models/2.jpg",
    "/images/products/baikal/models/3.jpg",
    "/images/products/baikal/models/4.jpg",
    "/images/products/baikal/models/5.jpg",
    "/images/products/baikal/models/6.jpg",
    "/images/products/baikal/models/7.jpg",
    "/images/products/baikal/models/8.jpg",
    "/images/products/baikal/models/9.jpg",
    "/images/products/baikal/models/10.jpg",
    "/images/products/baikal/models/11.jpg",
    "/images/products/baikal/models/12.jpg",
    "/images/products/baikal/models/13.jpg",
    "/images/products/baikal/models/14.jpg",
    "/images/products/baikal/models/15.jpg",
    "/images/products/baikal/models/16.jpg",
    "/images/products/baikal/models/17.jpg",
    "/images/products/baikal/models/18.jpg",
    "/images/products/baikal/models/19.jpg",
    "/images/products/baikal/models/20.jpg",
    "/images/products/baikal/models/21.jpg",
    "/images/products/baikal/models/22.jpg",
    "/images/products/baikal/models/23.jpg",
    "/images/products/baikal/models/24.jpg",
    "/images/products/baikal/models/25.jpg",
    "/images/products/baikal/models/26.jpg",
    "/images/products/baikal/models/27.jpg",
    "/images/products/baikal/models/28.jpg",
    "/images/products/baikal/models/29.jpg",
    "/images/products/baikal/models/30.jpg",
    "/images/products/baikal/models/31.jpg",
  ],
  description:
    "Стул «Байкал» имеет прекрасный лаконичный и утончённый внешний облик. Каркас выполнен из красивой и прочной древесины Дуба.   Высокая спинка с боковыми поддержками и без подлокотников является одновременно удобной и при этом имеет лёгкий конструктив, создающий яркий визуальный образ.  В отделке спинки и сидушки использованы различные виды ткани, а также натуральной кожи, которые  сочетании с фактурой натурального дуба наполняют общий образ особенным очарованием и теплотой.",
  designer: "Сергей Беляков",
  dateOfCreation: 2022,
  countertop: [
    "ткань категория 1",
    "ткань категория 2",
    "ткань категория 3",
    "кожа категория 1",
    "кожа категория 2",
  ],
  underframe: ["массив дуба"],
  sizesSlider: ["/images/products/baikal/sizes/1.jpg"],
  visualisations: [
    "/images/products/baikal/interior/1.jpg",
    "/images/products/baikal/interior/2.jpg",
    "/images/products/baikal/interior/3.jpg",
    "/images/products/baikal/interior/4.jpg",
    "/images/products/baikal/interior/5.jpg",
    "/images/products/baikal/interior/6.jpg",
    "/images/products/baikal/interior/7.jpg",
    "/images/products/baikal/interior/8.jpg",
    "/images/products/baikal/interior/9.jpg",
  ],
  designersProjects: [],
  price: [36900],
  params: {
    "ткань категория 1": {
      "600 Х 550 Х 780": 36900,
    },
    "ткань категория 2": {
      "600 Х 550 Х 780": 39700,
    },
    "ткань категория 3": {
      "600 Х 550 Х 780": 48700,
    },
    "кожа категория 1": {
      "600 Х 550 Х 780": 48700,
    },
    "кожа категория 2": {
      "600 Х 550 Х 780": 57700,
    },
  },
  category: "CHAIR",
  name: "байкал",
  previewImg: "/images/products/baikal/preview.jpg",
  position: 13,
  mobilePosition: 7,
  model: "https://disk.yandex.ru/d/DSNCm8zEX0RB5A",
  collage: "https://disk.yandex.ru/d/Sh_kfg61NBZHoQ",
  tags: ["стул"],
};
