export const baikal_mt = {
  id: 3,
  title: "baikal-mt",
  modelsSlider: [
    "/images/products/baikal-mt/models/1.jpg",
    "/images/products/baikal-mt/models/2.jpg",
    "/images/products/baikal-mt/models/3.jpg",
    "/images/products/baikal-mt/models/4.jpg",
    "/images/products/baikal-mt/models/5.jpg",
    "/images/products/baikal-mt/models/6.jpg",
    "/images/products/baikal-mt/models/7.jpg",
    "/images/products/baikal-mt/models/8.jpg",
    "/images/products/baikal-mt/models/9.jpg",
    "/images/products/baikal-mt/models/10.jpg",
    "/images/products/baikal-mt/models/11.jpg",
    "/images/products/baikal-mt/models/12.jpg",
    "/images/products/baikal-mt/models/13.jpg",
    "/images/products/baikal-mt/models/14.jpg",
    "/images/products/baikal-mt/models/15.jpg",
    "/images/products/baikal-mt/models/16.jpg",
    "/images/products/baikal-mt/models/17.jpg",
    "/images/products/baikal-mt/models/18.jpg",
    "/images/products/baikal-mt/models/19.jpg",
    "/images/products/baikal-mt/models/20.jpg",
    "/images/products/baikal-mt/models/21.jpg",
  ],
  description:
    "Стул «Байкал МТ» имеет прекрасный лаконичный и утончённый внешний облик. Каркас выполнен из металла.   Высокая спинка с боковыми поддержками и без подлокотников является одновременно удобной и при этом имеет лёгкий конструктив, создающий яркий визуальный образ.  В отделке спинки и сидушки использованы различные виды ткани, а также натуральной кожи, которые  сочетании с металлом наполняют общий образ особым очарованием.",
  designer: "Сергей Беляков",
  dateOfCreation: 2022,
  countertop: [
    "ткань категория 1",
    "ткань категория 2",
    "кожа категория 1",
    "кожа категория 2",
  ],
  underframe: ["металл"],
  sizesSlider: ["/images/products/baikal-mt/sizes/1.jpg"],
  visualisations: [
    "/images/products/baikal-mt/interior/1.jpg",
    "/images/products/baikal-mt/interior/2.jpg",
    "/images/products/baikal-mt/interior/3.jpg",
    "/images/products/baikal-mt/interior/4.jpg",
    "/images/products/baikal-mt/interior/5.jpg",
    "/images/products/baikal-mt/interior/6.jpg",
    "/images/products/baikal-mt/interior/7.jpg",
    "/images/products/baikal-mt/interior/8.jpg",
    "/images/products/baikal-mt/interior/9.jpg",
    "/images/products/baikal-mt/interior/10.jpg",
    "/images/products/baikal-mt/interior/11.jpg",
    "/images/products/baikal-mt/interior/12.jpg",
  ],
  designersProjects: [],
  price: [29000],
  params: {
    "ткань категория 1": {
      "600 Х 550 Х 780": 29900,
    },
    "ткань категория 2": {
      "600 Х 550 Х 780": 32400,
    },
    "кожа категория 1": {
      "600 Х 550 Х 780": 42200,
    },
    "кожа категория 2": {
      "600 Х 550 Х 780": 50500,
    },
  },
  category: "CHAIR",
  name: "байкал мт",
  previewImg: "/images/products/baikal-mt/preview.jpg",
  position: 11,
  mobilePosition: 8,
  model: "https://disk.yandex.ru/d/YeghFNMIWAhmsQ",
  tags: ["стул"],
};
