export const buton = {
  id: 5,
  title: "buton",
  modelsSlider: [
    "/images/products/buton/models/1.jpg",
    "/images/products/buton/models/2.jpg",
    "/images/products/buton/models/3.jpg",
    "/images/products/buton/models/4.jpg",
    "/images/products/buton/models/5.jpg",
    "/images/products/buton/models/6.jpg",
    "/images/products/buton/models/7.jpg",
    "/images/products/buton/models/8.jpg",
    "/images/products/buton/models/9.jpg",
    "/images/products/buton/models/10.jpg",
    "/images/products/buton/models/11.jpg",
    "/images/products/buton/models/12.jpg",
    "/images/products/buton/models/13.jpg",
    "/images/products/buton/models/14.jpg",
    "/images/products/buton/models/15.jpg",
    "/images/products/buton/models/16.jpg",
    "/images/products/buton/models/17.jpg",
    "/images/products/buton/models/18.jpg",
    "/images/products/buton/models/19.jpg",
    "/images/products/buton/models/20.jpg",
    "/images/products/buton/models/21.jpg",
    "/images/products/buton/models/22.jpg",
    "/images/products/buton/models/23.jpg",
    "/images/products/buton/models/24.jpg",
  ],
  description:
    "Столик из серии БУТОН - очень универсальный. Может служить как журнальным столиком, так и прикроватным.  Верх столика может быть выполнен из матового инновационного материала FENIX*, шпона дуба или hpl-пластика 'под мрамор'. Ножка столика сделана из металлической пластины в форме скругленного прямоугольника.",
  designer: "Сергей Беляков",
  dateOfCreation: 2019,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/buton/sizes/1.jpg",
    "/images/products/buton/sizes/2.jpg",
  ],
  visualisations: [
    "/images/products/buton/interiors/1.jpg",
    "/images/products/buton/interiors/2.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/buton/projects/1.jpg",
    },
    {
      img: "/images/products/buton/projects/2.jpg",
      author: "юлия мостовщикова (@yumost.design)",
    },
    {
      img: "/images/products/buton/projects/3.jpg",
      author: "юлия мостовщикова (@yumost.design)",
    },
    {
      img: "/images/products/buton/projects/4.jpg",
      author: "юлия мостовщикова (@yumost.design)",
    },
    {
      img: "/images/products/buton/projects/5.jpg",
      author: "юлия мостовщикова (@yumost.design)",
    },
    {
      img: "/images/products/buton/projects/6.jpg",
      author: "silva gonian design",
    },
    {
      img: "/images/products/buton/projects/7.jpg",
      author: "студия А + Б",
    },
    {
      img: "/images/products/buton/projects/8.jpg",
      author: "Людмила Розводовская (ELLE Decoration)",
    },
    {
      img: "/images/products/buton/projects/9.jpg",
      author: "Ольга Шарлай",
    },
    {
      img: "/images/products/buton/projects/10.jpg",
      author: "Чернышова Виктория",
    },
  ],
  price: [21500],
  params: {
    "hpl / fenix ntm": {
      "450 Х 450": 25200,
      "600 Х 450": 29300,
      "600 Х 600": 29300,
      "600 Х 750": 29300,
      "600 Х 350 Х 720": 22700,
    },
    "шпон дуба": {
      "450 Х 450": 21500,
      "600 Х 450": 23600,
      "600 Х 600": 23600,
      "600 Х 750": 23600,
      "600 Х 350 Х 720": 23100,
    },
  },
  category: "COFFEE_TABLE STEAL",
  name: "бутон",
  previewImg: "/images/products/buton/preview.jpg",
  position: 28,
  sortedPosition: 26,
  mobilePosition: 18,
  model: "https://disk.yandex.ru/d/xtqwTJfUCZ89gQ",
  tags: ["стол", "журнальный"],
};
