export const flakon = {
  id: 6,
  title: "flakon",
  modelsSlider: [
    "/images/products/flakon/models/3.jpg",
    "/images/products/flakon/models/1.jpg",
    "/images/products/flakon/models/2.jpg",
    "/images/products/flakon/models/4.jpg",
    "/images/products/flakon/models/5.jpg",
    "/images/products/flakon/models/6.jpg",
    "/images/products/flakon/models/7.jpg",
    "/images/products/flakon/models/8.jpg",
    "/images/products/flakon/models/9.jpg",
    "/images/products/flakon/models/10.jpg",
    "/images/products/flakon/models/11.jpg",
    "/images/products/flakon/models/12.jpg",
    "/images/products/flakon/models/13.jpg",
    "/images/products/flakon/models/14.jpg",
    "/images/products/flakon/models/15.jpg",
    "/images/products/flakon/models/16.jpg",
    "/images/products/flakon/models/17.jpg",
    "/images/products/flakon/models/18.jpg",
    "/images/products/flakon/models/19.jpg",
    "/images/products/flakon/models/20.jpg",
    "/images/products/flakon/models/21.jpg",
    "/images/products/flakon/models/22.jpg",
    "/images/products/flakon/models/23.jpg",
  ],
  description:
    "Стол ФЛАКОН обладает лаконичным, строгим дизайном. Безупречность форм достигается при помощи использования большого количества металлических элементов - двухсоставной металлической опоры, пояса из железа вокруг столешницы.  Разнообразие цветовых решений для данной модели стола достигается возможностью комбинировать варианты покраски каждой из частей металлической опоры, а так же пояса и самой столешницы. Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор', шпонированного дубом МДФ.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/flakon/sizes/1.jpg",
    "/images/products/flakon/sizes/2.jpg",
    "/images/products/flakon/sizes/3.jpg",
  ],
  visualisations: [
    "/images/products/flakon/interior/1.jpg",
    "/images/products/flakon/interior/2.jpg",
    "/images/products/flakon/interior/3.jpg",
  ],
  designersProjects: [],
  price: [96400],
  params: {
    "hpl / fenix ntm": {
      "800 Х 750": 101100,
      "900 Х 750": 111000,
      "1000 Х 750	": 120500,
      "1100 Х 750": 129200,
      "1200 Х 750	": 130200,
      "1270 Х 750": 145700,
    },
    "шпон дуба": {
      "800 Х 750": 96400,
      "900 Х 750": 106000,
      "1000 Х 750	": 115400,
      "1100 Х 750": 123800,
      "1200 Х 750	": 132400,
      "1270 Х 750": 141800,
      "1400 Х 750": 159300,
      "1500 Х 750	": 170200,
      "1600 Х 750": 193100,
    },
  },
  category: "TABLE_CIRCLE STEAL",
  name: "флакон",
  previewImg: "/images/products/flakon/preview.jpg",
  position: 3,
  sortedPosition: 3,
  mobilePosition: 5,
  model: "https://disk.yandex.ru/d/MtNSEUzVUwVm8w",
  tags: ["стол", "круглый"],
};
