export const flakon = {
  id: 6,
  title: "flakon",
  modelsSlider: [
    "/images/products/flakon/models/3.jpg",
    "/images/products/flakon/models/1.jpg",
    "/images/products/flakon/models/2.jpg",
    "/images/products/flakon/models/4.jpg",
    "/images/products/flakon/models/5.jpg",
    "/images/products/flakon/models/6.jpg",
    "/images/products/flakon/models/7.jpg",
    "/images/products/flakon/models/8.jpg",
    "/images/products/flakon/models/9.jpg",
    "/images/products/flakon/models/10.jpg",
    "/images/products/flakon/models/11.jpg",
    "/images/products/flakon/models/12.jpg",
    "/images/products/flakon/models/13.jpg",
    "/images/products/flakon/models/14.jpg",
    "/images/products/flakon/models/15.jpg",
    "/images/products/flakon/models/16.jpg",
    "/images/products/flakon/models/17.jpg",
  ],
  description:
    "Стол ФЛАКОН обладает лаконичным, строгим дизайном. Безупречность форм достигается при помощи использования большого количества металлических элементов - двухсоставной металлической опоры, пояса из железа вокруг столешницы.  Разнообразие цветовых решений для данной модели стола достигается возможностью комбинировать варианты покраски каждой из частей металлической опоры, а так же пояса и самой столешницы. Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор', шпонированного дубом МДФ.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/flakon/sizes/1.jpg",
    "/images/products/flakon/sizes/2.jpg",
    "/images/products/flakon/sizes/3.jpg",
  ],
  visualisations: [
    "/images/products/flakon/interior/1.jpg",
    "/images/products/flakon/interior/2.jpg",
    "/images/products/flakon/interior/3.jpg",
  ],
  designersProjects: [],
  price: [106000],
  params: {
    "hpl / fenix ntm": {
      "800 Х 750": 111200,
      "900 Х 750": 122100,
      "1000 Х 750	": 132600,
      "1100 Х 750": 142100,
      "1200 Х 750	": 143200,
      "1270 Х 750": 160300,
    },
    "шпон дуба": {
      "800 Х 750": 106000,
      "900 Х 750": 116600,
      "1000 Х 750	": 126900,
      "1100 Х 750": 136200,
      "1200 Х 750	": 145600,
      "1270 Х 750": 156000,
      "1400 Х 750": 175200,
      "1500 Х 750	": 187200,
      "1600 Х 750": 212400,
    },
  },
  category: "TABLE_DINNER CIRCLE STEAL",
  name: "флакон",
  previewImg: "/images/products/flakon/preview.jpg",
  position: 3,
  sortedPosition: 3,
  mobilePosition: 4,
  model: "https://disk.yandex.ru/d/MtNSEUzVUwVm8w",
  collage: "https://disk.yandex.ru/d/Wh15GNRCYOFNcw",
  tags: ["стол", "круглый"],
};
