export const hameleon = {
  id: 9,
  title: "hameleon",
  modelsSlider: [
    "/images/products/hameleon/models/1.jpg",
    "/images/products/hameleon/models/2.jpg",
    "/images/products/hameleon/models/3.jpg",
    "/images/products/hameleon/models/4.jpg",
    "/images/products/hameleon/models/5.jpg",
    "/images/products/hameleon/models/6.jpg",
    "/images/products/hameleon/models/7.jpg",
    "/images/products/hameleon/models/8.jpg",
    "/images/products/hameleon/models/9.jpg",
    "/images/products/hameleon/models/10.jpg",
    "/images/products/hameleon/models/11.jpg",
    "/images/products/hameleon/models/12.jpg",
    "/images/products/hameleon/models/13.jpg",
    "/images/products/hameleon/models/14.jpg",
    "/images/products/hameleon/models/15.jpg",
    "/images/products/hameleon/models/16.jpg",
    "/images/products/hameleon/models/17.jpg",
    "/images/products/hameleon/models/18.jpg",
    "/images/products/hameleon/models/19.jpg",
    "/images/products/hameleon/models/20.jpg",
    "/images/products/hameleon/models/21.jpg",
    "/images/products/hameleon/models/22.jpg",
  ],
  description:
    "Столики из серии ХАМЕЛЕОН выполнены из металлического основания. Имеют две и столешницы: верхняя - из нанопластика FENIX*, нижняя - из массива дуба. Столики отлично впишутся в гостиную или кухню.",
  designer: "Сергей Беляков",
  dateOfCreation: 2019,
  countertop: ["hpl / fenix ntm"],
  underframe: ["металл"],
  sizesSlider: ["/images/products/hameleon/sizes/1.jpg"],
  visualisations: [
    "/images/products/hameleon/interior/1.jpg",
    "/images/products/hameleon/interior/2.jpg",
    "/images/products/hameleon/interior/3.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/hameleon/projects/1.jpg",
      author: "AMI ELLE Decoration",
    },
    {
      img: "/images/products/hameleon/projects/2.jpg",
      author: "AMI ELLE Decoration",
    },
    {
      img: "/images/products/hameleon/projects/3.jpg",
      author: "DKart design studio",
    },
    {
      img: "/images/products/hameleon/projects/4.jpg",
      author: "DKart design studio",
    },
    {
      img: "/images/products/hameleon/projects/5.jpg",
      author: "DKart design studio",
    },
    {
      img: "/images/products/hameleon/projects/6.jpg",
      author: "Ангелина Гладкова и Максим Саласин (ELLE Decoration)",
    },
    {
      img: "/images/products/hameleon/projects/7.jpg",
      author: "Ангелина Гладкова и Максим Саласин (ELLE Decoration)",
    },
    {
      img: "/images/products/hameleon/projects/8.jpg",
      author: "Людмила Розводовская (ELLE Decoration)",
    },
    {
      img: "/images/products/hameleon/projects/9.jpg",
      author: "Людмила Розводовская (ELLE Decoration)",
    },
    {
      img: "/images/products/hameleon/projects/10.jpg",
      author: "студия REDDOX",
    },
    {
      img: "/images/products/hameleon/projects/11.jpg",
      author: "Ульяночкин Алексей",
    },
  ],
  price: [28900],
  params: {
    "hpl / fenix ntm": {
      "500 Х 500": 28900,
      "600 Х 500": 31800,
      "900 Х 400": 48600,
    },
  },
  category: "COFFEE_TABLE STEAL",
  name: "хамелеон",
  previewImg: "/images/products/hameleon/preview.jpg",
  position: 24,
  sortedPosition: 24,
  mobilePosition: 15,
  model: "https://disk.yandex.ru/d/JoVrlvwUavirlQ",
  tags: ["стол", "журнальный"],
};
