export const klinker_f_r_k25 = {
  id: 38,
  title: "klinker-f-r-k25",
  modelsSlider: [
    "/images/products/klinker-f-r/klinker-f-r-k25/1.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/2.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/3.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/4.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/5.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/6.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/7.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/8.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/9.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/10.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/11.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/12.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/13.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/14.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k25/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон / эмаль", "керамика"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f-r/interior/k25-1.jpg",
    "/images/products/klinker-f-r/interior/k25-2.jpg",
  ],
  designersProjects: [],
  price: [261500],
  params: {
    "hpl / fenix ntm": {
      "1100/1515 Х 750": 269700,
      "1270/1720 Х 750": 297800,
    },
    "шпон / эмаль": {
      "1100/1515 Х 750": 261500,
      "1270/1720 Х 750": 283200,
    },
    "керамика": {
      "1100/1515 Х 750": 318800,
      "1270/1720 Х 750": 337400,
    },
  },
  category: "TABLE_DINNER TABLE_SLIDING",
  name: "клинкер-ф раздвижной к-25",
  previewImg: "/images/products/klinker-f-r/previewK25.jpg",
  model: "https://disk.yandex.ru/d/oVGywhPh19PlzQ",
  tags: ["стол", "круглый", "раздвижной"],
};

export const klinker_f_r_k50 = {
  id: 39,
  title: "klinker-f-r-k50",
  modelsSlider: [
    "/images/products/klinker-f-r/klinker-f-r-k50/1.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/2.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/3.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/4.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/5.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/6.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/7.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/8.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/9.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/10.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/11.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/12.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/13.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/14.jpg",
    "/images/products/klinker-f-r/klinker-f-r-k50/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон / эмаль", "керамика"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f-r/interior/k50-1.jpg",
    "/images/products/klinker-f-r/interior/k50-2.jpg",
  ],
  designersProjects: [],
  price: [261500],
  params: {
    "hpl / fenix ntm": {
      "1100/1515 Х 750": 269700,
      "1270/1720 Х 750": 297800,
    },
    "шпон / эмаль": {
      "1100/1515 Х 750": 261500,
      "1270/1720 Х 750": 283200,
    },
    "керамика": {
      "1100/1515 Х 750": 318800,
      "1270/1720 Х 750": 337400,
    },
  },
  category: "TABLE_DINNER TABLE_SLIDING",
  name: "клинкер-ф раздвижной к-50",
  previewImg: "/images/products/klinker-f-r/previewK50.jpg",
  model: "https://disk.yandex.ru/d/dDFs20XhHXidYw",
  tags: ["стол", "круглый", "раздвижной"],
};

export const klinker_f_r_p25 = {
  id: 40,
  title: "klinker-f-r-p25",
  modelsSlider: [
    "/images/products/klinker-f-r/klinker-f-r-p25/1.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/2.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/3.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/4.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/5.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/6.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/7.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/8.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/9.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/10.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/11.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/12.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/13.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/14.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p25/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон / эмаль", "керамика"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f-r/interior/p25-1.jpg",
    "/images/products/klinker-f-r/interior/p25-2.jpg",
  ],
  designersProjects: [],
  price: [261500],
  params: {
    "hpl / fenix ntm": {
      "1100/1515 Х 750": 269700,
      "1270/1720 Х 750": 297800,
    },
    "шпон / эмаль": {
      "1100/1515 Х 750": 261500,
      "1270/1720 Х 750": 283200,
    },
    "керамика": {
      "1100/1515 Х 750": 318800,
      "1270/1720 Х 750": 337400,
    },
  },
  category: "TABLE_DINNER TABLE_SLIDING",
  name: "клинкер-ф раздвижной п-25",
  previewImg: "/images/products/klinker-f-r/previewP25.jpg",
  model: "https://disk.yandex.ru/d/U2rJ4-vRVua-gg",
  tags: ["стол", "круглый", "раздвижной"],
};

export const klinker_f_r_p50 = {
  id: 41,
  title: "klinker-f-r-p50",
  modelsSlider: [
    "/images/products/klinker-f-r/klinker-f-r-p50/1.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/2.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/3.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/4.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/5.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/6.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/7.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/8.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/9.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/10.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/11.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/12.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/13.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/14.jpg",
    "/images/products/klinker-f-r/klinker-f-r-p50/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон / эмаль", "керамика"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f-r/interior/p50-1.jpg",
    "/images/products/klinker-f-r/interior/p50-2.jpg",
  ],
  designersProjects: [],
  price: [246800],
  params: {
    "hpl / fenix ntm": {
      "1100/1515 Х 750": 254500,
      "1270/1720 Х 750": 281000,
    },
    "шпон / эмаль": {
      "1100/1515 Х 750": 246800,
      "1270/1720 Х 750": 267200,
    },
    "керамика": {
      "1100/1515 Х 750": 300800,
      "1270/1720 Х 750": 318400,
    },
  },
  category: "TABLE_DINNER TABLE_SLIDING",
  name: "клинкер-ф раздвижной п-50",
  previewImg: "/images/products/klinker-f-r/previewP50.jpg",
  model: "https://disk.yandex.ru/d/YMf5JmCrCb-_ng",
  tags: ["стол", "круглый", "раздвижной"],
};
