export const klinker_f_k25 = {
  id: 34,
  title: "klinker-f-k25",
  modelsSlider: [
    "/images/products/klinker-f/klinker-f-k25/1.jpg",
    "/images/products/klinker-f/klinker-f-k25/2.jpg",
    "/images/products/klinker-f/klinker-f-k25/3.jpg",
    "/images/products/klinker-f/klinker-f-k25/4.jpg",
    "/images/products/klinker-f/klinker-f-k25/5.jpg",
    "/images/products/klinker-f/klinker-f-k25/6.jpg",
    "/images/products/klinker-f/klinker-f-k25/7.jpg",
    "/images/products/klinker-f/klinker-f-k25/8.jpg",
    "/images/products/klinker-f/klinker-f-k25/9.jpg",
    "/images/products/klinker-f/klinker-f-k25/10.jpg",
    "/images/products/klinker-f/klinker-f-k25/11.jpg",
    "/images/products/klinker-f/klinker-f-k25/12.jpg",
    "/images/products/klinker-f/klinker-f-k25/13.jpg",
    "/images/products/klinker-f/klinker-f-k25/14.jpg",
    "/images/products/klinker-f/klinker-f-k25/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f/interior/k25-1.jpg",
    "/images/products/klinker-f/interior/k25-2.jpg",
  ],
  designersProjects: [],
  price: [194400],
  params: {
    "hpl / fenix ntm": {
      "1100 Х 750": 211600,
      "1270 Х 750": 226200,
    },
    "шпон дуба": {
      "1100 Х 750": 194400,
      "1270 Х 750": 207900,
    },
  },
  category: "TABLE_CIRCLE",
  name: "клинкер-ф к-25",
  previewImg: "/images/products/klinker-f/previewK25.jpg",
  model: "https://disk.yandex.ru/d/Djz3e7R_6Sjd9g",
  tags: ["стол", "круглый"],
};

export const klinker_f_k50 = {
  id: 35,
  title: "klinker-f-k50",
  modelsSlider: [
    "/images/products/klinker-f/klinker-f-k50/1.jpg",
    "/images/products/klinker-f/klinker-f-k50/2.jpg",
    "/images/products/klinker-f/klinker-f-k50/3.jpg",
    "/images/products/klinker-f/klinker-f-k50/4.jpg",
    "/images/products/klinker-f/klinker-f-k50/5.jpg",
    "/images/products/klinker-f/klinker-f-k50/6.jpg",
    "/images/products/klinker-f/klinker-f-k50/7.jpg",
    "/images/products/klinker-f/klinker-f-k50/8.jpg",
    "/images/products/klinker-f/klinker-f-k50/9.jpg",
    "/images/products/klinker-f/klinker-f-k50/10.jpg",
    "/images/products/klinker-f/klinker-f-k50/11.jpg",
    "/images/products/klinker-f/klinker-f-k50/12.jpg",
    "/images/products/klinker-f/klinker-f-k50/13.jpg",
    "/images/products/klinker-f/klinker-f-k50/14.jpg",
    "/images/products/klinker-f/klinker-f-k50/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f/interior/k50-1.jpg",
    "/images/products/klinker-f/interior/k50-2.jpg",
  ],
  designersProjects: [],
  price: [185300],
  params: {
    "hpl / fenix ntm": {
      "1100 Х 750": 201700,
      "1270 Х 750": 215600,
    },
    "шпон дуба": {
      "1100 Х 750": 185300,
      "1270 Х 750": 198100,
    },
  },
  category: "TABLE_CIRCLE",
  name: "клинкер-ф к-50",
  previewImg: "/images/products/klinker-f/previewK50.jpg",
  model: "https://disk.yandex.ru/d/Atfey0TGKWT3iw",
  tags: ["стол", "круглый"],
};

export const klinker_f_p25 = {
  id: 36,
  title: "klinker-f-p25",
  modelsSlider: [
    "/images/products/klinker-f/klinker-f-p25/1.jpg",
    "/images/products/klinker-f/klinker-f-p25/2.jpg",
    "/images/products/klinker-f/klinker-f-p25/3.jpg",
    "/images/products/klinker-f/klinker-f-p25/4.jpg",
    "/images/products/klinker-f/klinker-f-p25/5.jpg",
    "/images/products/klinker-f/klinker-f-p25/6.jpg",
    "/images/products/klinker-f/klinker-f-p25/7.jpg",
    "/images/products/klinker-f/klinker-f-p25/8.jpg",
    "/images/products/klinker-f/klinker-f-p25/9.jpg",
    "/images/products/klinker-f/klinker-f-p25/10.jpg",
    "/images/products/klinker-f/klinker-f-p25/11.jpg",
    "/images/products/klinker-f/klinker-f-p25/12.jpg",
    "/images/products/klinker-f/klinker-f-p25/13.jpg",
    "/images/products/klinker-f/klinker-f-p25/14.jpg",
    "/images/products/klinker-f/klinker-f-p25/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f/interior/p25-1.jpg",
    "/images/products/klinker-f/interior/p25-2.jpg",
  ],
  designersProjects: [],
  price: [185300],
  params: {
    "hpl / fenix ntm": {
      "1100 Х 750": 201700,
      "1270 Х 750": 215600,
    },
    "шпон дуба": {
      "1100 Х 750": 185300,
      "1270 Х 750": 198100,
    },
  },
  category: "TABLE_CIRCLE",
  name: "клинкер-ф п-25",
  previewImg: "/images/products/klinker-f/previewP25.jpg",
  model: "https://disk.yandex.ru/d/MK5mPgxwktAKzA",
  tags: ["стол", "круглый"],
};

export const klinker_f_p50 = {
  id: 37,
  title: "klinker-f-p50",
  modelsSlider: [
    "/images/products/klinker-f/klinker-f-p50/1.jpg",
    "/images/products/klinker-f/klinker-f-p50/2.jpg",
    "/images/products/klinker-f/klinker-f-p50/3.jpg",
    "/images/products/klinker-f/klinker-f-p50/4.jpg",
    "/images/products/klinker-f/klinker-f-p50/5.jpg",
    "/images/products/klinker-f/klinker-f-p50/6.jpg",
    "/images/products/klinker-f/klinker-f-p50/7.jpg",
    "/images/products/klinker-f/klinker-f-p50/8.jpg",
    "/images/products/klinker-f/klinker-f-p50/9.jpg",
    "/images/products/klinker-f/klinker-f-p50/10.jpg",
    "/images/products/klinker-f/klinker-f-p50/11.jpg",
    "/images/products/klinker-f/klinker-f-p50/12.jpg",
    "/images/products/klinker-f/klinker-f-p50/13.jpg",
    "/images/products/klinker-f/klinker-f-p50/14.jpg",
    "/images/products/klinker-f/klinker-f-p50/15.jpg",
  ],
  description:
    "Столы серии 'Клинкер' обладают уникальным дизайном с большим количеством рельефов и широкой цветовой палитрой.  По индивидуальному запросу можно выбрать любой цвет эмали по каталогу RAL. Подстолье и обратная сторона крышки могут иметь как глянцевую, так и матовую поверхность.  Покрытие столешницы может быть выполнено из нанопластика FENIX NTM, HPL пластика 'под мрамор'. При диаметре столешницы до 950 мм. возможно покрытие из керамики толщиной 6 мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["эмаль"],
  sizesSlider: ["/images/products/klinker-f/sizes/1.jpg"],
  visualisations: [
    "/images/products/klinker-f/interior/p50-1.jpg",
    "/images/products/klinker-f/interior/p50-2.jpg",
  ],
  designersProjects: [],
  price: [173200],
  params: {
    "hpl / fenix ntm": {
      "1100 Х 750": 188400,
      "1270 Х 750": 201400,
    },
    "шпон дуба": {
      "1100 Х 750": 173200,
      "1270 Х 750": 185100,
    },
  },
  category: "TABLE_CIRCLE",
  name: "клинкер-ф п-50",
  previewImg: "/images/products/klinker-f/previewP50.jpg",
  model: "https://disk.yandex.ru/d/rNZ9bxuuOFCBVg",
  tags: ["стол", "круглый"],
};
