export const nimb = {
  id: 44,
  title: "nimb",
  modelsSlider: [
    "/images/products/nimb/models/1.jpg",
    "/images/products/nimb/models/2.jpg",
    "/images/products/nimb/models/3.jpg",
    "/images/products/nimb/models/4.jpg",
    "/images/products/nimb/models/5.jpg",
    "/images/products/nimb/models/6.jpg",
    "/images/products/nimb/models/7.jpg",
    "/images/products/nimb/models/8.jpg",
    "/images/products/nimb/models/9.jpg",
    "/images/products/nimb/models/10.jpg",
    "/images/products/nimb/models/11.jpg",
    "/images/products/nimb/models/12.jpg",
  ],
  description:
    "Ряд столиков из серии НИМБ незаметно впишутся в интерьер Вашей гостиной или спальни. Невесомость конструкции обеспечивают тонкие, но прочные стальные стержни. Верх может быть изготовлен из массива дуба, нанопластика FENIX NTM, hpl-пластик 'под мрамор'.",
  designer: "Сергей Беляков",
  dateOfCreation: 2019,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: ["/images/products/nimb/sizes/1.jpg"],
  visualisations: [ "/images/products/nimb/interior/1.jpg"],
  designersProjects: [
    {
      img: "/images/products/nimb/projects/1.jpg",
      author: "Студия дизайна интерьера Ananev architects",
    },
    {
      img: "/images/products/nimb/projects/2.jpg",
      author: "Студия дизайна интерьера Ananev architects",
    },
    {
      img: "/images/products/nimb/projects/3.jpg",
      author: "Юлия Русанова",
    },
    {
      img: "/images/products/nimb/projects/4.jpg",
      author: "Светлана Вершинина",
    },
  ],
  price: [32700],
  params: {
    "hpl / fenix ntm": {
      "350 Х 350": 34800,
      "450 Х 450": 38700,
      "600 Х 400": 45800,
      "900 Х 350": 64700,
    },
    "шпон дуба": {
      "350 Х 350": 32700,
      "450 Х 450": 36200,
      "600 Х 400": 43300,
      "900 Х 350": 63300,
    },
  },
  category: "COFFEE_TABLE STEAL",
  name: "нимб",
  previewImg: "/images/products/nimb/preview.jpg",
  position: 74,
  sortedPosition: 39,
  mobilePosition: 74,
  model: "https://disk.yandex.ru/d/o-GPTbTwfQza-Q",
  collage: "https://disk.yandex.ru/d/cAS7yK5DhniQtg",
  tags: ["стол", "журнальный"],
};
