export const orbita = {
  id: 46,
  title: "orbita",
  modelsSlider: [
    "/images/products/orbita/models/1.jpg",
    "/images/products/orbita/models/2.jpg",
    "/images/products/orbita/models/3.jpg",
    "/images/products/orbita/models/4.jpg",
    "/images/products/orbita/models/5.jpg",
    "/images/products/orbita/models/6.jpg",
    "/images/products/orbita/models/7.jpg",
    "/images/products/orbita/models/8.jpg",
    "/images/products/orbita/models/9.jpg",
    "/images/products/orbita/models/10.jpg",
    "/images/products/orbita/models/11.jpg",
    "/images/products/orbita/models/12.jpg",
    "/images/products/orbita/models/13.jpg",
    "/images/products/orbita/models/14.jpg",
    "/images/products/orbita/models/15.jpg",
    "/images/products/orbita/models/16.jpg",
    "/images/products/orbita/models/17.jpg",
  ],
  description:
    "Стол классической круглой формы с уникальной кромкой столешницы, которая представляет из себя цельносварной стальной обруч. Металлическое подстолье представлено в трёх размерах,  совмещенных с широким размерным рядом столешниц , имеющих  диаметр с от 800 до 1600мм. с шагом 100мм. Столешница может быть выполнена из шпона дуба, нанопластика FENIX NTM, hpl пластика 'под мрамор'. К классической палитре добавлены цвета металлик, в которых данная модель смотрится особенно вкусно.",
  designer: "Сергей Беляков",
  dateOfCreation: 2022,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/orbita/sizes/1.jpg",
    "/images/products/orbita/sizes/2.jpg",
    "/images/products/orbita/sizes/3.jpg",
  ],
  visualisations: [
    "/images/products/orbita/interior/1.jpg",
    "/images/products/orbita/interior/2.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/orbita/projects/2.jpg",
      author: "IMPETUS",
    },
    {
      img: "/images/products/orbita/projects/3.jpg",
      author: "IMPETUS",
    },
    {
      img: "/images/products/orbita/projects/4.jpg",
      author: "Светлана Вершинина",
    },
    {
      img: "/images/products/orbita/projects/5.jpg",
      author: "Светлана Вершинина",
    },
    {
      img: "/images/products/orbita/projects/6.jpg",
      author: "Юлия Злобина",
    },
    {
      img: "/images/products/orbita/projects/7.jpg",
      author: "Юлия Злобина",
    },
    {
      img: "/images/products/orbita/projects/8.jpg",
      author: "Ирина Жиган",
    },
    {
      img: "/images/products/orbita/projects/10.jpg",
      author: "Анастасия Чебышева (anche-design)",
    },
  ],
  price: [71800],
  params: {
    'hpl / fenix ntm': {
      "800 Х 750": 76500,
      "900 Х 750": 86000,
      "1000 Х 750": 95300,
      "1100 Х 750": 103800,
      "1200 Х 750": 104800,
      "1300 Х 750": 119900,
    },
    'шпон дуба': {
      "800 Х 750": 71800,
      "900 Х 750": 81200,
      "1000 Х 750": 90300,
      "1100 Х 750": 98600,
      "1200 Х 750": 107000,
      "1300 Х 750": 116100,
      "1400 Х 750": 133200,
      "1500 Х 750": 143700,
      "1600 Х 750": 155000,
    },
  },
  category: "TABLE_DINNER CIRCLE STEAL",
  name: "орбита",
  previewImg: "/images/products/orbita/preview.jpg",
  position: 12,
  sortedPosition: 5,
  mobilePosition: 39,
  model: "https://disk.yandex.ru/d/rvO62ZpNVQL5og",
  collage: "https://disk.yandex.ru/d/6ILK0KTJObrVgg",
  tags: ["стол", "круглый"],
};
