export const orbita_m = {
  id: 47,
  title: "orbita-m",
  modelsSlider: [
    "/images/products/orbita-m/models/1.jpg",
    "/images/products/orbita-m/models/2.jpg",
    "/images/products/orbita-m/models/3.jpg",
    "/images/products/orbita-m/models/4.jpg",
    "/images/products/orbita-m/models/5.jpg",
    "/images/products/orbita-m/models/6.jpg",
    "/images/products/orbita-m/models/7.jpg",
    "/images/products/orbita-m/models/8.jpg",
    "/images/products/orbita-m/models/9.jpg",
    "/images/products/orbita-m/models/10.jpg",
    "/images/products/orbita-m/models/11.jpg",
    "/images/products/orbita-m/models/12.jpg",
    "/images/products/orbita-m/models/13.jpg",
    "/images/products/orbita-m/models/14.jpg",
    "/images/products/orbita-m/models/15.jpg",
    "/images/products/orbita-m/models/16.jpg",
    "/images/products/orbita-m/models/17.jpg",
    "/images/products/orbita-m/models/18.jpg",
    "/images/products/orbita-m/models/19.jpg",
    "/images/products/orbita-m/models/20.jpg",
    "/images/products/orbita-m/models/21.jpg",
    "/images/products/orbita-m/models/22.jpg",
    "/images/products/orbita-m/models/23.jpg",
    "/images/products/orbita-m/models/24.jpg",
    "/images/products/orbita-m/models/25.jpg",
    "/images/products/orbita-m/models/26.jpg",
    "/images/products/orbita-m/models/27.jpg",
  ],
  description:
    "Журнальный столик «Орбита» имеет классическую круглую форму с уникальной кромкой столешницы, которая представляет из себя цельносварной стальной обруч. Металлическое подстолье представлено в трёх размерах,  совмещенных с широким размерным рядом столешниц, имеющих  диаметр с от 500 до 1400мм.  Столешница может быть выполнена из шпона дуба, нанопластика FENIX NTM, hpl пластика 'под мрамор'. К классической палитре добавлены цвета металлик, в которых данная модель смотрится особенно вкусно.  Размерный ряд журнальных столиков «Орбита» включает в себя три варианта опоры стола  по высоте, что позволяет составлять из нескольких столиков интересные композиции в интерьере.",
  designer: "Сергей Беляков",
  dateOfCreation: 2022,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/orbita-m/sizes/1.jpg",
    "/images/products/orbita-m/sizes/2.jpg",
    "/images/products/orbita-m/sizes/3.jpg",
    "/images/products/orbita-m/sizes/4.jpg",
  ],
  visualisations: [
    "/images/products/orbita-m/interior/1.jpg",
    "/images/products/orbita-m/interior/2.jpg",
    "/images/products/orbita-m/interior/3.jpg",
    "/images/products/orbita-m/interior/4.jpg",
  ],
  designersProjects: [],
  price: [44500],
  params: {
    "hpl / fenix ntm": {
      "500 Х 520": 48900,
      "600 Х 600": 55900,
      "800 Х 430": 78800,
      "900 Х 430": 84800,
      "1000 Х 430": 92000,
      "1100 Х 430": 98800,
      "1200 Х 430": 107800,
      "1300 Х 430": 115700,
    },
    "шпон дуба": {
      "500 Х 520": 44500,
      "600 Х 600": 51400,
      "800 Х 430": 77900,
      "900 Х 430": 83900,
      "1000 Х 430": 91600,
      "1100 Х 430": 99600,
      "1200 Х 430": 109400,
      "1300 Х 430": 117900,
    },
  },
  category: "COFFEE_TABLE STEAL",
  name: "орбита-м",
  previewImg: "/images/products/orbita-m/preview.jpg",
  position: 17,
  sortedPosition: 15,
  mobilePosition: 30,
  model: "https://disk.yandex.ru/d/GKkBshdfs-1A_Q",
  tags: ["стол", "журнальный"],
};
