export const orbita_m = {
  id: 47,
  title: "orbita-m",
  modelsSlider: [
    "/images/products/orbita-m/models/1.jpg",
    "/images/products/orbita-m/models/2.jpg",
    "/images/products/orbita-m/models/3.jpg",
    "/images/products/orbita-m/models/4.jpg",
    "/images/products/orbita-m/models/5.jpg",
    "/images/products/orbita-m/models/6.jpg",
    "/images/products/orbita-m/models/7.jpg",
    "/images/products/orbita-m/models/8.jpg",
    "/images/products/orbita-m/models/9.jpg",
    "/images/products/orbita-m/models/10.jpg",
    "/images/products/orbita-m/models/11.jpg",
    "/images/products/orbita-m/models/12.jpg",
    "/images/products/orbita-m/models/13.jpg",
    "/images/products/orbita-m/models/14.jpg",
    "/images/products/orbita-m/models/15.jpg",
    "/images/products/orbita-m/models/16.jpg",
    "/images/products/orbita-m/models/17.jpg",
    "/images/products/orbita-m/models/18.jpg",
    "/images/products/orbita-m/models/19.jpg",
    "/images/products/orbita-m/models/20.jpg",
    "/images/products/orbita-m/models/21.jpg",
  ],
  description:
    "Журнальный столик «Орбита» имеет классическую круглую форму с уникальной кромкой столешницы, которая представляет из себя цельносварной стальной обруч. Металлическое подстолье представлено в трёх размерах,  совмещенных с широким размерным рядом столешниц, имеющих  диаметр с от 500 до 1400мм.  Столешница может быть выполнена из шпона дуба, нанопластика FENIX NTM, hpl пластика 'под мрамор'. К классической палитре добавлены цвета металлик, в которых данная модель смотрится особенно вкусно.  Размерный ряд журнальных столиков «Орбита» включает в себя три варианта опоры стола  по высоте, что позволяет составлять из нескольких столиков интересные композиции в интерьере.",
  designer: "Сергей Беляков",
  dateOfCreation: 2022,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/orbita-m/sizes/1.jpg",
    "/images/products/orbita-m/sizes/2.jpg",
    "/images/products/orbita-m/sizes/3.jpg",
    "/images/products/orbita-m/sizes/4.jpg",
  ],
  visualisations: [
    "/images/products/orbita-m/interior/1.jpg",
    "/images/products/orbita-m/interior/2.jpg",
    "/images/products/orbita-m/interior/3.jpg",
    "/images/products/orbita-m/interior/4.jpg",
  ],
  designersProjects: [],
  price: [49000],
  params: {
    "hpl / fenix ntm": {
      "500 Х 520": 53800,
      "600 Х 600": 61500,
      "800 Х 430": 86700,
      "900 Х 430": 93300,
      "1000 Х 430": 101200,
      "1100 Х 430": 108700,
      "1200 Х 430": 118600,
      "1300 Х 430": 127300,
    },
    "шпон дуба": {
      "500 Х 520": 49000,
      "600 Х 600": 56500,
      "800 Х 430": 85700,
      "900 Х 430": 92300,
      "1000 Х 430": 100800,
      "1100 Х 430": 109600,
      "1200 Х 430": 120300,
      "1300 Х 430": 129700,
    },
  },
  category: "COFFEE_TABLE STEAL",
  name: "орбита-м",
  previewImg: "/images/products/orbita-m/preview.jpg",
  position: 16.5,
  sortedPosition: 15,
  mobilePosition: 32,
  model: "https://disk.yandex.ru/d/GKkBshdfs-1A_Q",
  collage: "https://disk.yandex.ru/d/yvm1oSWOGttqXQ",
  tags: ["стол", "журнальный"],
};
