export const pud = {
  id: 48,
  title: "pud",
  modelsSlider: [
    "/images/products/pud/models/1.jpg",
    "/images/products/pud/models/2.jpg",
    "/images/products/pud/models/3.jpg",
    "/images/products/pud/models/4.jpg",
    "/images/products/pud/models/5.jpg",
    "/images/products/pud/models/6.jpg",
    "/images/products/pud/models/7.jpg",
    "/images/products/pud/models/8.jpg",
    "/images/products/pud/models/9.jpg",
    "/images/products/pud/models/10.jpg",
    "/images/products/pud/models/11.jpg",
    "/images/products/pud/models/12.jpg",
    "/images/products/pud/models/13.jpg",
  ],
  description:
    "Стол ПУД отлично подходит как для улицы, так и для дома. Может быть выполнен в нескольких вариантах столешниц: компакт-плита (для уличных пространств); шпон дуба, FENIX NTM, hpl-пластик 'под мрамор'. Имеет разные варианты по высоте: стандартная высота обеденного стола 750мм, высота журнального стола 500мм и высота барного стола 1100мм.",
  designer: "Сергей Беляков",
  dateOfCreation: 2021,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["архитектурный бетон"],
  sizesSlider: [
    "/images/products/pud/sizes/1.jpg",
    "/images/products/pud/sizes/2.jpg",
    "/images/products/pud/sizes/3.jpg",
  ],
  visualisations: ["/images/products/pud/interior/1.jpg",
  "/images/products/pud/interior/2.jpg"],
  designersProjects: [],
  price: [37800],
  params: {
    "hpl / fenix ntm": {
      "600 Х 750": 41500,
      "700 Х 750": 46500,
      "800 Х 750": 52200,
      "900 Х 750": 58600,
    },
    "шпон дуба": {
      "600 Х 750": 37800,
      "700 Х 750": 42500,
      "800 Х 750": 47800,
      "900 Х 750": 53900,
    },
  },
  category: "COFFEE_TABLE TABLE_DINNER BAR STEAL",
  name: "пуд",
  previewImg: "/images/products/pud/preview.jpg",
  position: 35,
  sortedPosition: 71,
  mobilePosition: 27,
  model: "https://disk.yandex.ru/d/ijxweUe-6oRuXg",
  collage: "https://disk.yandex.ru/d/7xdKR7kGPb0TPg",
  tags: ["стол", "обеденный", "журнальный", "барный"],
};
