export const rol = {
  id: 50,
  title: "rol",
  modelsSlider: [
    "/images/products/rol/models/1.jpg",
    "/images/products/rol/models/2.jpg",
    "/images/products/rol/models/3.jpg",
    "/images/products/rol/models/4.jpg",
    "/images/products/rol/models/5.jpg",
    "/images/products/rol/models/6.jpg",
    "/images/products/rol/models/7.jpg",
    "/images/products/rol/models/8.jpg",
    "/images/products/rol/models/9.jpg",
    "/images/products/rol/models/10.jpg",
    "/images/products/rol/models/11.jpg",
    "/images/products/rol/models/12.jpg",
    "/images/products/rol/models/13.jpg",
    "/images/products/rol/models/14.jpg",
    "/images/products/rol/models/15.jpg",
    "/images/products/rol/models/16.jpg",
    "/images/products/rol/models/17.jpg",
    "/images/products/rol/models/18.jpg",
    "/images/products/rol/models/19.jpg",
    "/images/products/rol/models/20.jpg",
    "/images/products/rol/models/21.jpg",
    "/images/products/rol/models/22.jpg",
    "/images/products/rol/models/23.jpg",
    "/images/products/rol/models/24.jpg",
    "/images/products/rol/models/25.jpg",
    // "/images/products/rol/models/26.jpg",
    // "/images/products/rol/models/27.jpg",
    // "/images/products/rol/models/28.jpg",
    // "/images/products/rol/models/29.jpg",
    // "/images/products/rol/models/30.jpg",
    // "/images/products/rol/models/31.jpg",
    // "/images/products/rol/models/32.jpg",
    // "/images/products/rol/models/33.jpg",
    // "/images/products/rol/models/34.jpg",
    // "/images/products/rol/models/35.jpg",
    // "/images/products/rol/models/36.jpg",
    // "/images/products/rol/models/37.jpg",
  ],
  description:
    "Столики из серии РОЛ представлены в трех размерах: d900мм*h350мм; d600мм*h600мм, d500*h500. Основание выполнено из массива дуба, может ыть выкрашено в цвет согласно палитре. Столешница может быть выполнена из массива дуба, нанопластика FENIX NTM, hpl пластика 'под мрамор'.",
  designer: "Сергей Беляков",
  dateOfCreation: 2021,
  countertop: ["hpl / fenix ntm", "массив, шпон"],
  underframe: ["массив дуба"],
  sizesSlider: ["/images/products/rol/sizes/1.jpg"],
  visualisations: [
    "/images/products/rol/interior/1.jpg",
    "/images/products/rol/interior/2.jpg",
    "/images/products/rol/interior/3.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/rol/projects/1.jpg",
      author: "ArDi Architects",
    },
    {
      img: "/images/products/rol/projects/2.jpg",
      author: "ArDi Architects",
    },
    {
      img: "/images/products/rol/projects/3.jpg",
      author: "Студия дизайна интерьера FreshStyle48",
    },
    {
      img: "/images/products/rol/projects/4.jpg",
      author: "Студия дизайна интерьера FreshStyle48",
    },
    {
      img: "/images/products/rol/projects/5.jpg",
      author: "Дизайн-студия INTERI",
    },
    {
      img: "/images/products/rol/projects/6.jpg",
      author: "Анастасия Петросян (@interior.petrosian)",
    },
    {
      img: "/images/products/rol/projects/7.jpg",
      author: "Анастасия Петросян (@interior.petrosian)",
    },
    {
      img: "/images/products/rol/projects/8.jpg",
      author: "Анастасия Петросян (@interior.petrosian)",
    },
    {
      img: "/images/products/rol/projects/9.jpg",
      author: "Студия дизайна интерьера Savoe Interior's",
    },
    {
      img: "/images/products/rol/projects/10.jpg",
      author: "Артём Алексеев (@artalekseev.design)",
    },
    {
      img: "/images/products/rol/projects/11.jpg",
      author: "Алла Манухина",
    },
  ],
  price: [52600],
  params: {
    "hpl / fenix ntm": {
      "500 Х 500": 54900,
      "600 Х 600": 61000,
      "900 Х 350": 72200,
    },
    "шпон дуба": {
      "500 Х 500": 52600,
      "600 Х 600": 61000,
      "900 Х 350": 69600,
    },
  },
  category: "COFFEE_TABLE",
  name: "рол",
  previewImg: "/images/products/rol/preview.jpg",
  position: 21,
  sortedPosition: 20,
  mobilePosition: 25,
  model: "https://disk.yandex.ru/d/TyM2SaWV3S6Jjg",
  tags: ["стол", "журнальный"],
};
