export const tviks = {
  id: 67,
  title: "tviks",
  modelsSlider: [
    "/images/products/tviks/models/1.jpg",
    "/images/products/tviks/models/2.jpg",
    "/images/products/tviks/models/3.jpg",
    "/images/products/tviks/models/4.jpg",
    "/images/products/tviks/models/5.jpg",
    "/images/products/tviks/models/6.jpg",
    "/images/products/tviks/models/7.jpg",
    "/images/products/tviks/models/8.jpg",
    "/images/products/tviks/models/9.jpg",
    "/images/products/tviks/models/10.jpg",
    "/images/products/tviks/models/11.jpg",
    "/images/products/tviks/models/12.jpg",
    "/images/products/tviks/models/13.jpg",
    "/images/products/tviks/models/14.jpg",
    "/images/products/tviks/models/15.jpg",
    "/images/products/tviks/models/16.jpg",
    "/images/products/tviks/models/17.jpg",
  ],
  description:
    "Столы серии ТВИКС обладают хорошей устойчивостью и универсальным дизайном, что делает их подходящими как для ресторанов и кафе, так и для дома. Стол имеет прочную опору и царгу из массива дуба со сложными скругленными углами. Для увеличения устойчивости стола используется стальной фланец, который может быть покрыт порошковой краской или быть выполнен из нержавеющей стали. Столешница выполнена из тонкой плиты керамогранита. Разнообразие цветовых решений достигается возможностью комбинировать варианты тонирования деревянных деталей и отделки самой столешницы. На выбор покупателей имеется два варианта стола: с одной или двумя прямоугольными опорами.",
  designer: "Сергей Беляков",
  dateOfCreation: 2023,
  countertop: ["hpl / fenix ntm", "шпон дуба", "керамика"],
  underframe: ["массив дуба"],
  sizesSlider: ["/images/products/tviks/sizes/1.jpg"],
  visualisations: [
    "/images/products/tviks/interior/1.jpg",
    "/images/products/tviks/interior/2.jpg",
    "/images/products/tviks/interior/3.jpg",
  ],
  designersProjects: [],
  price: [59000],
  params: {
    "hpl / fenix ntm": {
      "600 X 600 X 750": 66000,
      "800 X 800 X 750": 79700,
      "900 X 900 X 750": 89000,
    }, 
    "шпон дуба": {
      "600 X 600 X 750": 59000,
      "800 X 800 X 750": 67200,
      "900 X 900 X 750": 73200,
    },
    "керамика": {
      "600 X 600 X 750": 88200,
      "800 X 800 X 750": 96400,
      "900 X 900 X 750": 102400,
    },
  },
  category: "TABLE_DINNER CIRCLE OAK STEEL",
  name: "твикс",
  previewImg: "/images/products/tviks/preview.jpg",
  position: 22,
  sortedPosition: 17,
  mobilePosition: 21,
  model: "https://disk.yandex.ru/d/GIyoLj42Siq65Q",
  collage: "https://disk.yandex.ru/d/hpsBMlavmJt7Ew",
  tags: ["стол"],
};
