export const velvet_oval_2 = {
  id: 58,
  title: "velvet-oval-2",
  modelsSlider: [
    "/images/products/velvet-oval-2/models/1.jpg",
    "/images/products/velvet-oval-2/models/2.jpg",
    "/images/products/velvet-oval-2/models/3.jpg",
    "/images/products/velvet-oval-2/models/4.jpg",
    "/images/products/velvet-oval-2/models/5.jpg",
    "/images/products/velvet-oval-2/models/6.jpg",
    "/images/products/velvet-oval-2/models/7.jpg",
    "/images/products/velvet-oval-2/models/8.jpg",
    "/images/products/velvet-oval-2/models/9.jpg",
    "/images/products/velvet-oval-2/models/10.jpg",
    "/images/products/velvet-oval-2/models/11.jpg",
    "/images/products/velvet-oval-2/models/12.jpg",
    "/images/products/velvet-oval-2/models/13.jpg",
    "/images/products/velvet-oval-2/models/14.jpg",
    "/images/products/velvet-oval-2/models/15.jpg",
  ],
  description:
    "Элегантный стол ВЕЛЬВЕТ также представлен в форме овала. Стол привлекает сочетанием геометрических форм и материалов. Столешница может быть выполнена из матового инновационного материала FENIX NTM, МДФ шпонированный дубом, hpl-пластик 'под мрамор'. Основание выполнено из металлических трубок, напоминающих фактуру вельвета. Овальный ВЕЛЬВЕТ представлен в варианте с одной овальной ногой либо с двумя круглыми в зависимости от габаритов столешницы.",
  designer: "Сергей Беляков",
  dateOfCreation: 2019,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/velvet-oval-2/sizes/1.jpg",
    "/images/products/velvet-oval-2/sizes/2.jpg",
    "/images/products/velvet-oval-2/sizes/3.jpg",
    "/images/products/velvet-oval-2/sizes/4.jpg",
  ],
  visualisations: [],
  designersProjects: [
    {
      img: "/images/products/velvet-oval-2/projects/1.jpg",
      author: "Polinastudio PRO",
    },
    {
      img: "/images/products/velvet-oval-2/projects/2.jpg",
      author: "Polinastudio PRO",
    },
    {
      img: "/images/products/velvet-oval-2/projects/3.jpg",
      author: "Янина Филиппова",
    },
    {
      img: "/images/products/velvet-oval-2/projects/4.jpg",
      author: "Янина Филиппова",
    },
  ],
  price: [191800],
  params: {
    "hpl / fenix ntm": {
      "1800 Х 1000 Х 750": 197500,
      "2400 Х 1200 Х 750": 221600,
      "2400 Х 1000 Х 750": 219200,
      "3000 Х 1200 Х 750": 296500,
    },
    "шпон дуба": {
      "1800 Х 1000 Х 750": 191800,
      "2400 Х 1200 Х 750": 216300,
      "2400 Х 1000 Х 750": 213200,
      "2750 Х 1200 Х 750": 275700,
    },
  },
  category: "TABLE_DINNER LONG STEAL",
  name: "вельвет овал 2",
  previewImg: "/images/products/velvet-oval-2/preview.jpg",
  position: 37,
  sortedPosition: 23,
  mobilePosition: 32,
  model: "https://disk.yandex.ru/d/W9PMQBoFXOPrtw",
  tags: ["стол", "обеденный"],
};
