export const velvet_krug_ju = {
  id: 55,
  title: "velvet-krug-ju",
  modelsSlider: [
    "/images/products/velvet-krug-ju/models/1.jpg",
    "/images/products/velvet-krug-ju/models/2.jpg",
    "/images/products/velvet-krug-ju/models/3.jpg",
    "/images/products/velvet-krug-ju/models/4.jpg",
    "/images/products/velvet-krug-ju/models/5.jpg",
    "/images/products/velvet-krug-ju/models/6.jpg",
    "/images/products/velvet-krug-ju/models/7.jpg",
    "/images/products/velvet-krug-ju/models/8.jpg",
    "/images/products/velvet-krug-ju/models/9.jpg",
    "/images/products/velvet-krug-ju/models/10.jpg",
    "/images/products/velvet-krug-ju/models/11.jpg",
  ],
  description:
    "В линейке стола ВЕЛЬВЕТ также представлена журнальная версия. В стандартной линейке столики представлены в трех размерах. Можно приобрести как группой, так и по отдельности. Столешница может быть выполнена из матового инновационного материала FENIX NTM, МДФ шпонированный дубом, hpl-пластик 'под мрамор'. Основание выполнено из металлических трубок, напоминающих фактуру вельвета.",
  designer: "Сергей Беляков",
  dateOfCreation: 2019,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/velvet-krug-ju/sizes/1.jpg",
    "/images/products/velvet-krug-ju/sizes/2.jpg",
  ],
  visualisations: [
    "/images/products/velvet-krug-ju/interior/1.jpg",
    "/images/products/velvet-krug-ju/interior/2.jpg",
    "/images/products/velvet-krug-ju/interior/3.jpg",
    "/images/products/velvet-krug-ju/interior/4.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/velvet-krug-ju/projects/1.jpg",
      author: "Студия дизайна INTERI",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/2.jpg",
      author: "Студия дизайна INTERI",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/3.jpg",
      author: "MATRYOSHKA",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/4.jpg",
      author: "MATRYOSHKA",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/5.jpg",
      author: "Студия интерьерного дизайна Diz Lab",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/6.jpg",
      author: "Студия дизайна интерьера Savoe Interior's",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/7.jpg",
      author: "Александр Савинов",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/8.jpg",
      author: "Владимир Сорокин",
    },
    {
      img: "/images/products/velvet-krug-ju/projects/9.jpg",
      author: "Яна Грошева",
    },
  ],
  price: [68200],
  params: {
    "hpl / fenix ntm": {
      "500 Х 400": 71800,
      "600 Х 400": 76800,
      "600 Х 450": 76800,
      "800 Х 450": 88800,
      "900 Х 320": 104400,
      "1000 Х 320": 112100,
      "1200 Х 320": 127200,
      "1200 Х 400": 127200,
    },
    "шпон дуба": {
      "500 Х 400": 68200,
      "600 Х 400": 72700,
      "600 Х 450": 72700,
      "800 Х 450": 83800,
      "900 Х 320": 99200,
      "1000 Х 320": 106600,
      "1200 Х 320": 121600,
      "1200 Х 400": 121600,
    },
  },
  category: "COFFEE_TABLE STEAL",
  name: "вельвет журнальный",
  previewImg: "/images/products/velvet-krug-ju/preview.jpg",
  position: 36,
  sortedPosition: 36,
  mobilePosition: 29,
  model: "https://disk.yandex.ru/d/2eDU-ZUq0wcqEw",
  collage: "https://disk.yandex.ru/d/56-z5Mlis-1SqQ",
  tags: ["стол", "журнальный"],
};
