export const velvet_sl_fl = {
  id: 61,
  title: "velvet-sl-fl",
  modelsSlider: [
    "/images/products/velvet-sl-fl/models/1.jpg",
    "/images/products/velvet-sl-fl/models/2.jpg",
    "/images/products/velvet-sl-fl/models/3.jpg",
    "/images/products/velvet-sl-fl/models/4.jpg",
    "/images/products/velvet-sl-fl/models/5.jpg",
    "/images/products/velvet-sl-fl/models/6.jpg",
    "/images/products/velvet-sl-fl/models/7.jpg",
    "/images/products/velvet-sl-fl/models/8.jpg",
  ],
  description:
    "Элегантный стол ВЕЛЬВЕТ также представлен в форме суперэллипса. Стол привлекает сочетанием геометрических форм и материалов. Столешница может быть выполнена из матового инновационного материала FENIX NTM, МДФ шпонированный дубом, hpl-пластик 'под мрамор'. Основание выполнено из металлических трубок, напоминающих фактуру вельвета. На размеры столешницы ....мм*900мм и менее стол выполнен с нижним основанием для большей устойчивости.",
  designer: "Сергей Беляков",
  dateOfCreation: 2021,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/velvet-sl-fl/sizes/1.jpg",
    "/images/products/velvet-sl-fl/sizes/2.jpg",
    "/images/products/velvet-sl-fl/sizes/3.jpg",
    "/images/products/velvet-sl-fl/sizes/4.jpg",
  ],
  visualisations: [],
  designersProjects: [
    {
      img: "/images/products/velvet-sl-fl/projects/1.jpg",
      author: "Marble Design Studio",
    },
    {
      img: "/images/products/velvet-sl-fl/projects/2.jpg",
      author: "Marble Design Studio",
    },
    {
      img: "/images/products/velvet-sl-fl/projects/3.jpg",
      author: "мария зайцева",
      artist: "дмитрий царёв",
    },
    {
      img: "/images/products/velvet-sl-fl/projects/4.jpg",
      author: "мария зайцева",
      artist: "дмитрий царёв",
    },
    {
      img: "/images/products/velvet-sl-fl/projects/5.jpg",
      author: "Евгений Блинов",
    },
    {
      img: "/images/products/velvet-sl-fl/projects/6.jpg",
      author: "Писарева",
    },
    {
      img: "/images/products/velvet-sl-fl/projects/7.jpg",
      author: "Писарева",
    },
  ],
  price: [117600],
  params: {
    "hpl / fenix ntm": {
      "1200 Х 750 Х 750": 123200,
      "1400 Х 950 Х 750": 141200,
      "1600 Х 950 Х 750": 163600,
      "1600 Х 1100 Х 750": 173300,
      "1800 Х 950 Х 750	": 171800,
      "1800 Х 1100 Х 750": 182400,
      "2000 Х 1100 Х 765": 219700,
    },
    "шпон дуба": {
      "1200 Х 750 Х 750": 117600,
      "1400 Х 950 Х 750": 135100,
      "1600 Х 950 Х 750": 157300,
      "1600 Х 1100 Х 750": 167100,
      "1800 Х 950 Х 750	": 165200,
      "1800 Х 1100 Х 750": 176100,
      "2000 Х 1100 Х 765": 213400,
    },
  },
  category: "TABLE_DINNER LONG STEAL",
  name: "вельвет сл с фланцем",
  previewImg: "/images/products/velvet-sl-fl/preview.jpg",
  position: 43,
  sortedPosition: 12,
  mobilePosition: 25,
  model: "https://disk.yandex.ru/d/_v9fXyOkRhS2uw",
  collage: "https://disk.yandex.ru/d/EvTtGt1Cprr2VQ",
  tags: ["стол", "обеденный"],
};
