export const velvet_oval_fl = {
  id: 62,
  title: "velvet-oval-fl",
  modelsSlider: [
    "/images/products/velvet-oval-fl/models/1.jpg",
    "/images/products/velvet-oval-fl/models/2.jpg",
    "/images/products/velvet-oval-fl/models/3.jpg",
    "/images/products/velvet-oval-fl/models/4.jpg",
    "/images/products/velvet-oval-fl/models/5.jpg",
    "/images/products/velvet-oval-fl/models/6.jpg",
    "/images/products/velvet-oval-fl/models/7.jpg",
    "/images/products/velvet-oval-fl/models/8.jpg",
    "/images/products/velvet-oval-fl/models/9.jpg",
  ],
  description:
    "Элегантный стол ВЕЛЬВЕТ также представлен в форме овала. Стол привлекает сочетанием геометрических форм и материалов. Столешница может быть выполнена из матового инновационного материала FENIX NTM, МДФ шпонированный дубом, hpl-пластик 'под мрамор'. Основание выполнено из металлических трубок, напоминающих фактуру вельвета. На размеры столешницы ....мм*900мм и менее стол выполнен с нижним основанием для большей устойчивости.",
  designer: "Сергей Беляков",
  dateOfCreation: 2021,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/velvet-oval-fl/sizes/1.jpg",
    "/images/products/velvet-oval-fl/sizes/2.jpg",
  ],
  visualisations: [],
  designersProjects: [],
  price: [141700],
  params: {
    "hpl / fenix ntm": {
      "1600 Х 950 Х 750": 147400,
      "1600 Х 1100 Х 750": 156100,
      "1800 Х 950 Х 750": 154800,
      "1800 Х 1100 Х 750": 162800,
    },
    "шпон дуба": {
      "1600 Х 950 Х 750": 141700,
      "1600 Х 1100 Х 750": 150500,
      "1800 Х 950 Х 750": 148800,
      "1800 Х 1100 Х 750": 157200,
    },
  },
  category: "TABLE_DINNER STEAL",
  name: "вельвет овал с фланцем",
  previewImg: "/images/products/velvet-oval-fl/preview.jpg",
  position: 31,
  sortedPosition: 28,
  mobilePosition: 20,
  model: "https://disk.yandex.ru/d/XM8b14drA1M5-A",
  tags: ["стол", "обеденный"],
};
