export const velvet_krug_razdvij = {
  id: 56,
  title: "velvet-krug-razdvij",
  modelsSlider: [
    "/images/products/velvet-krug-razdvij/models/1.jpg",
    "/images/products/velvet-krug-razdvij/models/2.jpg",
    "/images/products/velvet-krug-razdvij/models/3.jpg",
    "/images/products/velvet-krug-razdvij/models/4.jpg",
    "/images/products/velvet-krug-razdvij/models/5.jpg",
    "/images/products/velvet-krug-razdvij/models/6.jpg",
    "/images/products/velvet-krug-razdvij/models/7.jpg",
    "/images/products/velvet-krug-razdvij/models/8.jpg",
    "/images/products/velvet-krug-razdvij/models/9.jpg",
    "/images/products/velvet-krug-razdvij/models/10.jpg",
    "/images/products/velvet-krug-razdvij/models/11.jpg",
    "/images/products/velvet-krug-razdvij/models/12.jpg",
    "/images/products/velvet-krug-razdvij/models/13.jpg",
    "/images/products/velvet-krug-razdvij/models/14.jpg",
    "/images/products/velvet-krug-razdvij/models/15.jpg",
    "/images/products/velvet-krug-razdvij/models/16.jpg",
  ],
  description:
    "Стол представлен в двух размерах и нескольких вариантах материалов столешницы. Данная модель стола конструктивно  может быть изготовлена в двух вариантах: раздвижной и нераздвижной. Стол раскладывается из круга в овал. Нога сделана из дубовых ламелей, тонированных в различные цвета из палитры. Столешница может быть выполнена из МДФ, шпонированного дубом, нанопластика Fenix, hpl-пластика «под мрамор» и керамогранита. Нижний фланец сделан из нержавеющей стали. Ручная декоративная шлифовка с матовой поверхностью.  Складной механизм прост в эксплуатации, подойдёт для ежедневного использования. Сам механизм полностью скрыт царгой, как в сложенном, так и разложенном виде.",
  designer: "Сергей Беляков",
  dateOfCreation: 2021,
  countertop: ["hpl / fenix ntm", "шпон дуба", "керамика"],
  underframe: ["дубовые ламели"],
  sizesSlider: ["/images/products/velvet-krug-razdvij/sizes/1.jpg"],
  visualisations: [
    "/images/products/velvet-krug-razdvij/interior/1.jpg",
    "/images/products/velvet-krug-razdvij/interior/2.jpg",
    "/images/products/velvet-krug-razdvij/interior/3.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/velvet-krug-razdvij/projects/1.jpg",
      author: "Александра Чигинцева",
    },
    {
      img: "/images/products/velvet-krug-razdvij/projects/2.jpg",
      author: "Александра Чигинцева",
    },
    {
      img: "/images/products/velvet-krug-razdvij/projects/3.jpg",
      author: "Александр Савинов",
    },
    {
      img: "/images/products/velvet-krug-razdvij/projects/4.jpg",
      author: "Артём Алексеев",
    },
    {
      img: "/images/products/velvet-krug-razdvij/projects/5.jpg",
      author: "'LK' design studio",
    },
  ],
  price: [214100],
  params: {
    'hpl / fenix ntm': {
      "1100 / 1510 Х 750": 218000,
      "1270 / 1720 Х 750": 240700,
    },
    'шпон дуба': {
      "1100 / 1510 Х 750": 214100,
      "1270 / 1720 Х 750": 228300,
    },
    'керамика': {
      "1100 / 1510 Х 750": 264800,
      "1270 / 1720 Х 750": 279800,
    },
  },
  category: "TABLE_DINNER TABLE_SLIDING",
  name: "вельвет раздвижной",
  previewImg: "/images/products/velvet-krug-razdvij/preview.jpg",
  position: 5,
  sortedPosition: 10,
  mobilePosition: 6,
  model: "https://disk.yandex.ru/d/F421wZC1VBFV7A",
  collage: "https://disk.yandex.ru/d/hjYsKKE6JCY5tA",
  tags: ["стол", "круглый", "раздвижной"],
};
