export const velvet_sl = {
  id: 59,
  title: "velvet-sl",
  modelsSlider: [
    "/images/products/velvet-sl/models/1.jpg",
    "/images/products/velvet-sl/models/2.jpg",
    "/images/products/velvet-sl/models/3.jpg",
    "/images/products/velvet-sl/models/4.jpg",
    "/images/products/velvet-sl/models/5.jpg",
    "/images/products/velvet-sl/models/6.jpg",
    "/images/products/velvet-sl/models/7.jpg",
    "/images/products/velvet-sl/models/8.jpg",
    "/images/products/velvet-sl/models/9.jpg",
    "/images/products/velvet-sl/models/10.jpg",
    "/images/products/velvet-sl/models/11.jpg",
    "/images/products/velvet-sl/models/12.jpg",
    "/images/products/velvet-sl/models/13.jpg",
    "/images/products/velvet-sl/models/14.jpg",
    "/images/products/velvet-sl/models/15.jpg",
  ],
  description:
    "Элегантный стол ВЕЛЬВЕТ также представлен в форме суперэллипса. Стол привлекает сочетанием геометрических форм и материалов. Столешница может быть выполнена из матового инновационного материала FENIX NTM, МДФ шпонированный дубом, hpl-пластик 'под мрамор'. Основание выполнено из металлических трубок, напоминающих фактуру вельвета. ВЕЛЬВЕТ суперэллипс представлен в варианте с одной прямоугольной ногой либо с двумя квадратными в зависимости от габаритов столешницы.",
  designer: "Сергей Беляков",
  dateOfCreation: 2019,
  countertop: ["hpl / fenix ntm", "шпон дуба"],
  underframe: ["металл"],
  sizesSlider: [
    "/images/products/velvet-sl/sizes/0.jpg",
    "/images/products/velvet-sl/sizes/1.jpg",
    "/images/products/velvet-sl/sizes/2.jpg",
    "/images/products/velvet-sl/sizes/3.jpg",
    "/images/products/velvet-sl/sizes/4.jpg",
  ],
  visualisations: [
    "/images/products/velvet-sl/interior/1.jpg",
    "/images/products/velvet-sl/interior/2.jpg",
  ],
  designersProjects: [
    {
      img: "/images/products/velvet-sl/projects/1.jpg",
      author: "Студия BLACK HOUSE",
    },
    {
      img: "/images/products/velvet-sl/projects/2.jpg",
      author: "yucubedesign",
    },
    {
      img: "/images/products/velvet-sl/projects/3.jpg",
      author: "Александр Савинов",
    },
    {
      img: "/images/products/velvet-sl/projects/4.jpg",
      author: "Александр Савинов",
    },
    {
      img: "/images/products/velvet-sl/projects/5.jpg",
      author: "Ирина Молчановская",
    },
    {
      img: "/images/products/velvet-sl/projects/6.jpg",
      author: "Ирина Молчановская",
    },
    {
      img: "/images/products/velvet-sl/projects/7.jpg",
      author: "Эльвина А",
    },
    {
      img: "/images/products/velvet-sl/projects/8.jpg",
      author: "Эльвина А",
    },
    {
      img: "/images/products/velvet-sl/projects/9.jpg",
      author: "Алина Урсова",
    },
    {
      img: "/images/products/velvet-sl/projects/10.jpg",
      author: "Дарина Самарина",
    },
  ],
  price: [116200],
  params: {
    "hpl / fenix ntm": {
      "950 Х 750": 121700,
      "1100 Х 750": 134500,
      "1200 Х 950 Х 750": 137000,
      "1400 Х 950 Х 750": 145000,
      "1600 Х 950 Х 750": 159100,
      "1600 Х 1100 Х 750": 173500,
      "1800 Х 1100 Х 750": 182500,
      "2000 Х 1100 Х 765": 222800,
    },
    "шпон дуба": {
      "950 Х 750": 116200,
      "1100 Х 750": 128700,
      "1200 Х 950 Х 750": 131100,
      "1400 Х 950 Х 750": 138900,
      "1600 Х 950 Х 750": 151800,
      "1600 Х 1100 Х 750": 167500,
      "1800 Х 1100 Х 750": 176400,
      "2000 Х 1100 Х 765": 216400,
    },
  },
  category: "TABLE_DINNER LONG",
  name: "вельвет сл",
  previewImg: "/images/products/velvet-sl/preview.jpg",
  position: 24,
  sortedPosition: 20,
  mobilePosition: 37,
  model: "https://disk.yandex.ru/d/4hzOkmACcrLB7w",
  collage: "https://disk.yandex.ru/d/gHYkEl8ZbmfnVw",
  tags: ["стол", "обеденный"],
};
